import type {
  AutoLayoutContract,
  AuthoringLimitations,
  ComponentConstructionSpecification,
  ComponentGovernance,
  ComponentSpecId,
  ContentLimit,
  DesignExposedProperty,
  LocalizationContract,
  NestedAssetContract,
  ResponsiveContract,
  ResizingContract,
} from './types';

const reviewed = '2026-08-29';
const notApplicable = 'Not applicable because this export has no canvas geometry.';

const governance = (
  canonicalSource: string,
  ownerRole: string,
  componentPolicy: string
): ComponentGovernance => ({
  status: 'stable',
  ownerRole,
  lastReviewed: reviewed,
  canonicalSource,
  changePolicy: [
    componentPolicy,
    'A breaking property, token, or behavior change requires design and engineering approval, a migration note, and a major release.',
    'The design asset, implementation, documentation, accessibility contract, and regression coverage must ship in the same change.',
  ],
});

const layout = (
  direction: AutoLayoutContract['direction'],
  gap: string,
  padding: string,
  alignment: string,
  wrap: string,
  notes: string[] = []
): AutoLayoutContract => ({ applicable: true, direction, gap, padding, alignment, wrap, notes });

const noLayout = (reason: string): AutoLayoutContract => ({
  applicable: false,
  direction: 'none',
  gap: 'Not applicable',
  padding: 'Not applicable',
  alignment: 'Not applicable',
  wrap: 'Not applicable',
  notes: [reason],
});

const resize = (
  width: ResizingContract['width'],
  height: ResizingContract['height'],
  minWidth: string,
  maxWidth: string,
  minHeight: string,
  maxHeight: string,
  overflow: ResizingContract['overflow'],
  notes: string[] = []
): ResizingContract => ({
  applicable: true,
  width,
  height,
  minWidth,
  maxWidth,
  minHeight,
  maxHeight,
  overflow,
  notes,
});

const noResize = (reason: string): ResizingContract => ({
  applicable: false,
  width: 'not-applicable',
  height: 'not-applicable',
  minWidth: 'Not applicable',
  maxWidth: 'Not applicable',
  minHeight: 'Not applicable',
  maxHeight: 'Not applicable',
  overflow: 'not-applicable',
  notes: [reason],
});

const property = (
  name: string,
  label: string,
  type: DesignExposedProperty['type'],
  defaultValue: DesignExposedProperty['defaultValue'],
  codeMapping: string,
  options?: string[],
  required = false,
  notes?: string
): DesignExposedProperty => ({
  name,
  label,
  type,
  required,
  defaultValue,
  options,
  codeMapping,
  notes,
});

const nested = (
  name: string,
  kind: NestedAssetContract['kind'],
  required: boolean,
  description: string,
  codeMapping: string
): NestedAssetContract => ({ name, kind, required, description, codeMapping });

const limit = (
  target: string,
  value: string,
  overflowBehavior: string,
  rationale: string
): ContentLimit => ({ target, limit: value, overflowBehavior, rationale });

const localization = (
  translatable: string[],
  rtlBehavior: string[],
  stressCases: string[]
): LocalizationContract => ({ translatable, rtlBehavior, stressCases });

const responsive = (
  strategy: string,
  breakpoints: string[],
  behavior: string[]
): ResponsiveContract => ({ strategy, breakpoints, behavior });

const limitations = (
  figma: string[],
  code: string[],
  nA: string[] = []
): AuthoringLimitations => ({ figma, code, notApplicable: nA });

export const componentConstructionSpecs = {
  button: {
    asset: { kind: 'component', figmaName: 'Components/Actions/Button', localName: 'Button', canvasApplicability: 'Publish as a component set with variant and size axes plus boolean and swap properties.' },
    autoLayout: layout('horizontal', '8px', '8px 16px to 12px 32px by size', 'Center in both axes', 'No wrap', ['Use logical leading and trailing slots. The icon size is a square frame with centered content.']),
    resizing: resize('hug', 'fixed', '36px', 'Hug content or fill parent when Full width is true', '36px', '44px', 'visible', ['Text variants hug by default. Icon-only uses a fixed 44px square that is both the visual size and the interaction target.']),
    exposedProperties: [
      property('variant', 'Variant', 'variant', 'primary', 'variant', ['primary', 'secondary', 'destructive', 'ghost', 'filter', 'filter-active', 'icon']),
      property('size', 'Size', 'variant', 'md', 'size', ['inline', 'sm', 'md', 'lg', 'xl', 'icon']),
      property('fullWidth', 'Full width', 'boolean', false, 'fullWidth'),
      property('disabled', 'Disabled', 'boolean', false, 'disabled'),
      property('label', 'Label', 'slot', 'Save changes', 'children', undefined, true),
      property('leadingIcon', 'Leading icon', 'instance-swap', null, 'First child, decorative unless it supplies the icon-only accessible name'),
      property('trailingIcon', 'Trailing icon', 'instance-swap', null, 'Last child, mark decorative'),
    ],
    nestedAssets: [nested('Label', 'slot', true, 'Single-line action label.', 'children'), nested('Leading icon', 'slot', false, 'Optional 16px icon before the label.', 'children'), nested('Trailing icon', 'slot', false, 'Optional 16px icon after the label.', 'children')],
    contentLimits: [limit('Label', 'One line, recommended 2 to 24 characters, maximum 32', 'Never truncate; revise the label or allow the parent to allocate more width.', 'Action labels must remain immediately scannable.'), limit('Icons', 'At most one icon on either side', 'Remove redundant icons.', 'Multiple symbols compete with the action label.')],
    localization: localization(['Label', 'Accessible name'], ['Leading and trailing slots follow logical reading order.', 'Mirror directional icons; do not mirror universal symbols.'], ['Test at 200% text size.', 'Test a label at twice the English length.', 'Test an icon-only accessible name in every locale.']),
    responsive: responsive('Intrinsic sizing with a parent-controlled full-width option.', ['No internal breakpoint'], ['Keep hug width in toolbars.', 'Use Full width inside narrow stacked action areas.', 'The consuming layout decides when actions stack.']),
    limitations: limitations(['Figma interactive variants may demonstrate hover and press but cannot reproduce native button semantics.', 'Do not detach instances to make one-off sizes.'], ['Icon-only use requires an accessible name that is not represented by visual geometry.', 'buttonStyles can style another element but does not supply button behavior.']),
    governance: governance('src/components/Button.tsx', 'Design systems action primitive owner', 'A new variant or size must represent a reusable hierarchy need and include every interaction state.'),
  },
  badge: {
    asset: { kind: 'component', figmaName: 'Components/Feedback/Badge', localName: 'Badge', canvasApplicability: 'Publish as a component set with semantic tone variants and one text property.' },
    autoLayout: layout('horizontal', '0px', '2px 8px', 'Center in both axes', 'No wrap'),
    resizing: resize('hug', 'hug', 'Content width', 'Recommended 160px', '18px', 'One line', 'visible'),
    exposedProperties: [property('variant', 'Tone', 'variant', 'default', 'variant', ['default', 'muted', 'success', 'warning', 'error', 'info']), property('label', 'Label', 'text', 'Ready', 'children', undefined, true)],
    nestedAssets: [nested('Label', 'slot', true, 'Status or classification text.', 'children')],
    contentLimits: [limit('Label', 'One to three words, maximum 24 characters', 'Do not truncate; replace with shorter vocabulary.', 'A badge is compact metadata, not explanatory content.')],
    localization: localization(['Label'], ['Text follows the document direction; pill geometry is symmetric.'], ['Test status terminology in the longest supported locale.', 'Verify color-independent meaning after translation.']),
    responsive: responsive('Always intrinsic.', ['No internal breakpoint'], ['Do not force fill width.', 'Allow the parent row to wrap the whole badge as a unit.']),
    limitations: limitations(['Do not add interactive variants to the design asset.'], ['Badge remains a span and must not receive click behavior.']),
    governance: governance('src/components/Badge.tsx', 'Design systems feedback owner', 'Semantic tone names may change only with the shared status taxonomy.'),
  },
  surface: {
    asset: { kind: 'component', figmaName: 'Components/Layout/Surface', localName: 'Surface', canvasApplicability: 'Publish as a container component with nested content enabled.' },
    autoLayout: layout('vertical', 'Inherited from content', '0, 16px, 24px, 32px, 40px, or responsive 32px/48px', 'Stretch children horizontally', 'Content controlled', ['The component supplies padding only; child spacing belongs to the content composition.']),
    resizing: resize('fill', 'hug', '0px', 'Parent controlled', '0px', 'Content controlled', 'visible', ['Use fixed height only for an explicitly specified media or data region.']),
    exposedProperties: [property('variant', 'Variant', 'variant', 'default', 'variant', ['default', 'muted', 'accent', 'inset', 'success', 'warning', 'info', 'error']), property('padding', 'Padding', 'variant', 'none', 'padding', ['none', 'sm', 'md', 'lg', 'xl', 'responsive']), property('interaction', 'Interaction', 'variant', 'none', 'interaction', ['none', 'group', 'within']), property('content', 'Content', 'slot', null, 'children', undefined, true)],
    nestedAssets: [nested('Content', 'slot', true, 'Consumer-owned semantic content.', 'children')],
    contentLimits: [limit('Nested surfaces', 'Maximum one bordered child layer in ordinary product UI', 'Flatten excess wrappers or remove an inner border.', 'Repeated framed layers obscure hierarchy.')],
    localization: localization(['Nested content only'], ['Container geometry is direction-neutral; nested content owns direction.'], ['Test with long nested copy and mixed-direction content.']),
    responsive: responsive('Fill its parent while height follows content.', ['md: responsive padding changes from 32px to 48px'], ['Responsive padding is the only built-in breakpoint behavior.', 'Parent grids own column changes.']),
    limitations: limitations(['Interaction variants are visual demonstrations and do not make the Figma layer operable.'], ['Surface has no semantics or interaction by itself; use a semantic wrapper when needed.']),
    governance: governance('src/components/Surface.tsx', 'Design systems layout primitive owner', 'New variants must map to an approved semantic surface token pair.'),
  },
  notice: {
    asset: { kind: 'component', figmaName: 'Components/Feedback/Notice', localName: 'Notice', canvasApplicability: 'Publish tone variants with title, message, icon visibility, and alignment properties.' },
    autoLayout: layout('horizontal', '16px', '24px', 'Start; optional centered composition', 'Content wraps'),
    resizing: resize('fill', 'hug', '240px', 'Parent controlled', 'Content controlled', 'Content controlled', 'visible'),
    exposedProperties: [property('variant', 'Tone', 'variant', 'default', 'variant', ['default', 'info', 'success', 'warning', 'error']), property('title', 'Title', 'text', null, 'title'), property('message', 'Message', 'slot', null, 'children'), property('centered', 'Centered', 'boolean', false, 'centered'), property('hideIcon', 'Hide icon', 'boolean', false, 'hideIcon'), property('icon', 'Status icon', 'instance-swap', null, 'Derived from variant; custom replacement is design-only and needs implementation review')],
    nestedAssets: [nested('Surface', 'primitive', true, 'Semantic tone container.', '<Surface> inside Notice'), nested('Status icon', 'slot', false, 'Decorative icon derived from tone.', 'Internal variant icon'), nested('Body', 'slot', false, 'Supporting content and recovery guidance.', 'children')],
    contentLimits: [limit('Title', 'One line, recommended maximum 48 characters', 'Wrap only when localization requires it.', 'The outcome should be understandable at a glance.'), limit('Body', 'Two short paragraphs or 240 characters', 'Move complex guidance into adjacent content.', 'Live-region announcements must remain concise.')],
    localization: localization(['Title', 'Body'], ['Icon appears on the logical start side.', 'Tone icon does not mirror.'], ['Test long recovery instructions.', 'Verify announcement order in right-to-left mode.']),
    responsive: responsive('Fill the containing content column.', ['No internal breakpoint'], ['Allow copy to wrap.', 'At very narrow widths, use centered only when the surrounding design is also centered.']),
    limitations: limitations(['Prototype presentation does not reproduce live-region announcements.'], ['Custom role and aria-live values must remain aligned with severity.']),
    governance: governance('src/components/Notice.tsx', 'Design systems feedback owner', 'Tone behavior changes require accessibility review of role and announcement priority.'),
  },
  skeleton: {
    asset: { kind: 'component', figmaName: 'Components/Feedback/Skeleton', localName: 'Skeleton', canvasApplicability: 'Publish primitive shape presets but require authored compositions to match final content.' },
    autoLayout: layout('vertical', '8px for composition examples', '0px', 'Stretch or align to target content', 'Composition controlled', ['The exported code component is one block; multi-line examples are grouped instances.']),
    resizing: resize('fill', 'fixed', '16px', 'Parent controlled', '4px', 'Target content height', 'clip', ['Width and height must match the content being reserved.']),
    exposedProperties: [property('shape', 'Shape preset', 'variant', 'content', 'className sizing and radius utilities', ['content', 'text', 'avatar']), property('width', 'Width preset', 'variant', 'full', 'className width utility', ['short', 'medium', 'full'])],
    nestedAssets: [nested('Placeholder block', 'primitive', true, 'One decorative loading surface.', '<Skeleton className="..." />')],
    contentLimits: [limit('Composition', 'Represent only the primary visible structure, usually three to seven blocks', 'Remove low-value decorative placeholders.', 'Too many shapes create noise and inaccurate expectations.')],
    localization: localization([], ['Primitive geometry is direction-neutral; compositions follow content reading order.'], ['Verify placeholder widths are not based only on English copy.', 'Test reduced motion.']),
    responsive: responsive('Dimensions follow the final responsive content.', ['Use the same breakpoints as the resolved component'], ['Update shape count and widths with the final layout.', 'Prevent layout shift at every supported width.']),
    limitations: limitations(['Figma animation is illustrative and does not validate reduced-motion behavior.'], ['The primitive does not announce loading; the surrounding region must do so.']),
    governance: governance('src/components/Skeleton.tsx', 'Design systems feedback owner', 'New presets must correspond to repeated production content footprints.'),
  },
  'empty-state': {
    asset: { kind: 'component', figmaName: 'Components/Content/Empty state', localName: 'EmptyState', canvasApplicability: 'Publish icon, title, description, and action properties with nested action support.' },
    autoLayout: layout('vertical', '8px copy gap; 16px icon gap; 24px action gap', '32px mobile; 48px desktop', 'Center', 'Content wraps'),
    resizing: resize('fill', 'hug', '240px', 'Parent controlled', 'Content controlled', 'Content controlled', 'visible'),
    exposedProperties: [property('icon', 'Icon', 'instance-swap', null, 'icon'), property('title', 'Title', 'text', 'No projects yet', 'title', undefined, true), property('description', 'Description', 'text', null, 'description'), property('action', 'Action', 'slot', null, 'children')],
    nestedAssets: [nested('Surface', 'primitive', true, 'Muted responsive container.', 'Internal Surface'), nested('Icon', 'slot', false, 'Decorative 48px context icon.', 'icon'), nested('Action', 'slot', false, 'Usually one Button.', 'children')],
    contentLimits: [limit('Title', 'One line preferred, maximum two lines', 'Wrap to two lines; then revise.', 'The state should remain quickly identifiable.'), limit('Description', 'Maximum three lines or about 180 characters', 'Move longer onboarding guidance outside the component.', 'The empty state is an orientation point, not a help article.'), limit('Actions', 'One primary action, optional one secondary text link', 'Remove lower-priority actions.', 'A single next step reduces decision cost.')],
    localization: localization(['Title', 'Description', 'Action labels'], ['Centered composition is direction-neutral.', 'Directional action icons mirror.'], ['Test twice-length copy.', 'Test without an icon.', 'Test at 200% text size.']),
    responsive: responsive('Fill the empty collection region.', ['md: padding increases from 32px to 48px'], ['Copy remains centered.', 'Parent sets vertical placement and available height.']),
    limitations: limitations(['Do not detach to fit extra actions or long instructional content.'], ['Title is rendered as text, so the consumer must provide surrounding heading hierarchy when needed.']),
    governance: governance('src/components/EmptyState.tsx', 'Design systems content pattern owner', 'Copy templates and action hierarchy changes require content design review.'),
  },
  'error-report': {
    asset: { kind: 'component', figmaName: 'Components/Feedback/Error report', localName: 'ErrorReport', canvasApplicability: 'Publish collapsed, expanded, and copied interactive states as component variants.' },
    autoLayout: layout('vertical', '8px', 'Inherited 24px Notice padding', 'Stretch', 'Content wraps'),
    resizing: resize('fill', 'hug', '280px', 'Parent controlled', 'Content controlled', 'Content controlled', 'visible'),
    exposedProperties: [property('title', 'Title', 'text', 'Something went wrong', 'title'), property('message', 'Message', 'text', null, 'message', undefined, true), property('details', 'Debug details', 'text', null, 'details'), property('expanded', 'Expanded preview', 'boolean', false, 'Internal disclosure state; no public prop'), property('copied', 'Copied preview', 'boolean', false, 'Transient internal state; no public prop')],
    nestedAssets: [nested('Notice', 'subcomponent', true, 'Assertive error container.', '<Notice variant="error">'), nested('Disclosure', 'subcomponent', false, 'Controls diagnostic visibility.', 'Internal native button'), nested('Copy action', 'subcomponent', false, 'Copies sanitized diagnostics.', 'Internal Button')],
    contentLimits: [limit('Title', 'One line preferred', 'Allow localization wrap.', 'The failure category should remain concise.'), limit('Message', 'One or two sentences', 'Move troubleshooting steps below the component.', 'Users need a clear outcome and next step.'), limit('Details', 'Sanitized diagnostic text only, maximum practical payload 4KB', 'Provide a support attachment flow for larger logs.', 'Large or sensitive logs should not be exposed inline.')],
    localization: localization(['Title', 'Message', 'Disclosure label', 'Copy state'], ['Disclosure chevron mirrors in right-to-left layouts.', 'Diagnostic payload remains in its source direction.'], ['Test translated button labels.', 'Test mixed-direction stack traces.', 'Test an absent details value.']),
    responsive: responsive('Fill the failed content region.', ['No internal breakpoint'], ['Technical text wraps and remains horizontally scroll-safe.', 'Place the component near the failed content.']),
    limitations: limitations(['Clipboard and disclosure behavior must be annotated because Figma cannot validate browser permissions.'], ['Never pass credentials, tokens, personal data, or full URLs with sensitive query parameters to details.']),
    governance: governance('src/components/ErrorReport.tsx', 'Design systems reliability pattern owner', 'Changes to diagnostic content require privacy and security review.'),
  },
  field: {
    asset: { kind: 'component', figmaName: 'Components/Forms/Field', localName: 'Field family', canvasApplicability: 'Publish a nested field component with input and textarea instance swaps plus state properties.' },
    autoLayout: layout('vertical', '8px', '0px', 'Stretch', 'Content wraps', ['FieldGroup owns the sibling gap; FieldLabel, FieldLegend, controls, and FieldHint do not add exterior spacing.']),
    resizing: resize('fill', 'hug', '160px', 'Parent controlled', '44px plus labels and hints', 'Content controlled', 'visible'),
    exposedProperties: [property('control', 'Control', 'instance-swap', 'TextInput', 'TextInput or TextArea child', ['TextInput', 'TextArea']), property('label', 'Label', 'text', 'Label', 'FieldLabel children', undefined, true), property('hint', 'Hint or error', 'text', null, 'FieldHint children'), property('disabled', 'Disabled', 'boolean', false, 'disabled on the native control'), property('invalid', 'Invalid', 'boolean', false, 'aria-invalid on the native control plus semantic hint content'), property('required', 'Required', 'boolean', false, 'required on the native control and a localized label indicator')],
    nestedAssets: [nested('FieldGroup', 'primitive', true, 'Vertical field composition root.', 'FieldGroup'), nested('FieldLabel', 'subcomponent', true, 'Visible native label.', 'FieldLabel'), nested('Control', 'slot', true, 'TextInput, TextArea, or an equivalent labelled control.', 'TextInput, TextArea, or styled custom control'), nested('FieldHint', 'subcomponent', false, 'Description, requirement, or validation message.', 'FieldHint')],
    contentLimits: [limit('Label', 'One concise line preferred', 'Allow wrap, never truncate.', 'Every field needs an unambiguous name.'), limit('Hint or error', 'One or two short sentences', 'Move extended help outside the field.', 'Immediate guidance should be scannable.'), limit('Text area', 'Default visible size should cover the expected response, then grow or scroll', 'Use a counter or explicit maximum for constrained data.', 'Input size communicates expected content.')],
    localization: localization(['Label', 'Placeholder', 'Hint', 'Validation message'], ['Text and control direction follow the locale or the entered data type.', 'Required indicators stay next to the logical end of the label.'], ['Test labels at twice English length.', 'Test mixed-direction user input.', 'Test errors at 200% text size.']),
    responsive: responsive('Fill its form column.', ['No internal breakpoint'], ['Parent form controls column count.', 'Never reduce the control below 160px unless the data format explicitly allows it.']),
    limitations: limitations(['Figma properties cannot guarantee label, hint, and control ID associations.'], ['Consumers must connect htmlFor, id, aria-describedby, required, and aria-invalid correctly.']),
    governance: governance('src/components/Field.tsx', 'Design systems form foundations owner', 'New field primitives require form accessibility and validation-pattern review.'),
  },
  checkbox: {
    asset: { kind: 'component', figmaName: 'Components/Forms/Checkbox', localName: 'Checkbox', canvasApplicability: 'Publish checked, unchecked, disabled, hover, and focus states with a text property.' },
    autoLayout: layout('horizontal', '10px', '0px', 'Center vertically', 'Label wraps'),
    resizing: resize('hug', 'hug', '44px interaction area recommended', 'Parent controlled', '44px target recommended', 'Content controlled', 'visible'),
    exposedProperties: [property('checked', 'Checked', 'boolean', false, 'checked', undefined, true), property('disabled', 'Disabled', 'boolean', false, 'disabled'), property('label', 'Label', 'text', 'I agree', 'label', undefined, true)],
    nestedAssets: [nested('Native input', 'primitive', true, 'Visually hidden checkbox that owns semantics.', '<input type="checkbox">'), nested('Indicator', 'subcomponent', true, '16px visual check surface.', 'Internal visual span'), nested('Label', 'slot', true, 'Visible choice label.', 'label')],
    contentLimits: [limit('Label', 'One sentence, recommended maximum two lines', 'Wrap naturally; do not truncate.', 'The consequence of the choice must remain explicit.')],
    localization: localization(['Label'], ['Indicator sits on the logical start side.', 'Checkmark does not mirror.'], ['Test two-line labels.', 'Test 200% text size and a 44px minimum target.']),
    responsive: responsive('Hug content up to the parent width.', ['No internal breakpoint'], ['Label wraps while indicator remains aligned to the first line.', 'Parent controls list spacing.']),
    limitations: limitations(['Prototype checked state does not validate native input behavior.'], ['Component is controlled; the consumer must update checked in onChange.']),
    governance: governance('src/components/Checkbox.tsx', 'Design systems form foundations owner', 'State or target-size changes require input accessibility review.'),
  },
  'radio-group': {
    asset: { kind: 'component', figmaName: 'Components/Forms/Radio group', localName: 'RadioGroup', canvasApplicability: 'Publish vertical and horizontal group variants with nested option instances.' },
    autoLayout: layout('vertical', '12px between legend and options; 12px options vertically or 24px horizontally', '0px', 'Start', 'Horizontal options may wrap'),
    resizing: resize('fill', 'hug', '200px', 'Parent controlled', 'Content controlled', 'Content controlled', 'visible'),
    exposedProperties: [property('orientation', 'Orientation', 'variant', 'vertical', 'orientation', ['vertical', 'horizontal']), property('value', 'Selected value', 'variant', null, 'value', undefined, true), property('disabled', 'Disabled', 'boolean', false, 'disabled'), property('legend', 'Legend', 'text', 'Choose one', 'legend', undefined, true), property('options', 'Options', 'slot', null, 'options', undefined, true)],
    nestedAssets: [nested('Fieldset', 'primitive', true, 'Semantic group boundary.', '<fieldset>'), nested('Legend', 'subcomponent', true, 'Group question or name.', '<legend>'), nested('Radio option', 'subcomponent', true, 'Repeatable native radio, indicator, and label.', 'RadioOption data item')],
    contentLimits: [limit('Options', 'Recommended two to seven choices', 'Use Dropdown or a searchable picker for larger sets.', 'All choices should be comparable without excessive scanning.'), limit('Option label', 'One line preferred, maximum two lines', 'Wrap and align indicator with the first line.', 'Peer choices need parallel, concise wording.')],
    localization: localization(['Legend', 'Option labels'], ['Options flow from logical start; horizontal arrow behavior follows browser radio semantics.', 'Selection indicator does not mirror.'], ['Test the longest option in horizontal layout.', 'Test mixed enabled and disabled options.']),
    responsive: responsive('Vertical is the safe default.', ['Parent-selected narrow breakpoint'], ['Change horizontal groups to vertical before labels collide.', 'Do not change option order between widths.']),
    limitations: limitations(['Figma variants cannot reproduce native arrow-key selection.'], ['Values are stable domain keys and must not be translated even when labels are.']),
    governance: governance('src/components/RadioGroup.tsx', 'Design systems form foundations owner', 'Orientation or option behavior changes require keyboard-navigation review.'),
  },
  toggle: {
    asset: { kind: 'component', figmaName: 'Components/Forms/Toggle', localName: 'Toggle', canvasApplicability: 'Publish on, off, disabled, hover, focus, and pressed states with a label property.' },
    autoLayout: layout('horizontal', '10px', '0px', 'Center vertically', 'Label wraps'),
    resizing: resize('hug', 'hug', '44px', 'Parent controlled', '44px', 'Content controlled', 'visible'),
    exposedProperties: [property('checked', 'On', 'boolean', false, 'checked', undefined, true), property('disabled', 'Disabled', 'boolean', false, 'disabled'), property('label', 'Label', 'text', 'Enable notifications', 'label', undefined, true)],
    nestedAssets: [nested('Switch button', 'primitive', true, 'Native button with switch semantics.', '<button role="switch">'), nested('Track', 'subcomponent', true, '40px by 24px state surface.', 'Internal span'), nested('Thumb', 'subcomponent', true, '16px moving state indicator.', 'Internal span'), nested('Label', 'slot', true, 'Setting name.', 'label')],
    contentLimits: [limit('Label', 'Short setting phrase, maximum two lines', 'Wrap; never truncate.', 'The on and off consequence must be clear from the label and context.')],
    localization: localization(['Label'], ['Track remains visually consistent; label follows logical order.', 'Do not reverse the semantic meaning of the checked state.'], ['Test a two-line label.', 'Verify switch announcement in localized screen-reader output.']),
    responsive: responsive('Intrinsic control within a parent settings row.', ['No internal breakpoint'], ['Parent may place explanatory copy below.', 'Maintain a 44px minimum target.']),
    limitations: limitations(['Prototype motion does not validate aria-checked.'], ['The component is controlled and represents an immediate setting, not a deferred form choice.']),
    governance: governance('src/components/Toggle.tsx', 'Design systems form foundations owner', 'Changes to state meaning or motion require accessibility and interaction review.'),
  },
  slider: {
    asset: { kind: 'component', figmaName: 'Components/Forms/Slider', localName: 'Slider', canvasApplicability: 'Publish value, disabled, and value-label properties with a number property for the thumb position.' },
    autoLayout: layout('vertical', '8px', '0px', 'Stretch', 'No wrap inside track'),
    resizing: resize('fill', 'hug', '160px', 'Parent controlled', '44px including label and target', 'Content controlled', 'visible'),
    exposedProperties: [property('value', 'Value', 'number', 50, 'value', undefined, true), property('min', 'Minimum', 'number', 0, 'min'), property('max', 'Maximum', 'number', 100, 'max'), property('step', 'Step', 'number', 1, 'step'), property('showValue', 'Show value', 'boolean', true, 'showValue'), property('disabled', 'Disabled', 'boolean', false, 'disabled'), property('label', 'Label', 'text', 'Value', 'label', undefined, true)],
    nestedAssets: [nested('Label row', 'subcomponent', true, 'Label and optional formatted value.', 'Internal label/value elements'), nested('Range input', 'primitive', true, 'Native range control and focus target.', '<input type="range">'), nested('Track and thumb', 'subcomponent', true, 'CSS-painted current value representation.', 'Internal range styling')],
    contentLimits: [limit('Label', 'One concise line', 'Wrap only when required by localization.', 'The adjusted quantity should be immediately clear.'), limit('Displayed value', 'One short formatted number and unit', 'Use compact localized formatting.', 'Long prose does not belong in the value slot.')],
    localization: localization(['Label', 'Formatted value and unit'], ['Document direction controls the track progression where platform conventions require it.', 'Use locale-aware number and unit formatting.'], ['Test decimal separators.', 'Test long units.', 'Test minimum, maximum, and an invalid out-of-range input.']),
    responsive: responsive('Track fills its form column.', ['No internal breakpoint'], ['Keep at least 160px of usable track width.', 'Pair with direct numeric entry when precision is critical.']),
    limitations: limitations(['Figma number properties demonstrate position but not keyboard increments.'], ['min must be less than max, step must be positive, and value must remain within the range.']),
    governance: governance('src/components/Slider.tsx', 'Design systems form foundations owner', 'Range, formatting, or keyboard changes require input accessibility review.'),
  },
  dropdown: {
    asset: { kind: 'component', figmaName: 'Components/Forms/Dropdown', localName: 'Dropdown', canvasApplicability: 'Publish closed and open variants with nested option instances and selected state.' },
    autoLayout: layout('vertical', '8px label gap; 4px trigger to menu', '0px', 'Stretch', 'Menu options do not wrap by default'),
    resizing: resize('fill', 'hug', '200px', 'Parent controlled', '44px closed', 'Menu maximum 240px plus trigger', 'visible', ['Menu width matches the trigger and scrolls after its maximum height.']),
    exposedProperties: [property('label', 'Label', 'text', 'Select option', 'label', undefined, true), property('value', 'Selected value', 'variant', null, 'value', undefined, true), property('placeholder', 'Placeholder', 'text', 'Select an option', 'placeholder'), property('disabled', 'Disabled', 'boolean', false, 'disabled'), property('open', 'Open preview', 'boolean', false, 'Internal Headless UI state; no public prop'), property('options', 'Options', 'slot', null, 'options', undefined, true)],
    nestedAssets: [nested('Listbox label', 'primitive', true, 'Accessible field label.', 'ListboxLabel'), nested('Trigger', 'subcomponent', true, 'Current value and chevron button.', 'ListboxButton'), nested('Options panel', 'subcomponent', true, 'Anchored, scrollable menu.', 'ListboxOptions'), nested('Option', 'subcomponent', true, 'Repeatable selected, active, or disabled row.', 'DropdownOption data item')],
    contentLimits: [limit('Options', 'Recommended two to fifteen options', 'Use search or autocomplete for larger datasets.', 'A long unfiltered list is inefficient.'), limit('Option label', 'One line, recommended maximum 40 characters', 'Truncate visually only when the full value is otherwise available.', 'Menu scanning depends on concise parallel labels.')],
    localization: localization(['Label', 'Placeholder', 'Option labels'], ['Text and chevron align to logical sides.', 'Menu anchors to logical start.'], ['Test longest option.', 'Test a translated placeholder.', 'Test keyboard navigation in right-to-left mode.']),
    responsive: responsive('Trigger fills its form column; menu matches trigger width.', ['No internal breakpoint'], ['Keep the menu inside the viewport.', 'Use a full-screen selection pattern only in a product-level mobile adaptation.']),
    limitations: limitations(['Figma open state does not validate focus movement, collision handling, or scrolling.'], ['Options use stable untranslated values and localized labels.']),
    governance: governance('src/components/Dropdown.tsx', 'Design systems form foundations owner', 'Selection behavior changes require Headless UI parity and keyboard testing.'),
  },
  tabs: {
    asset: { kind: 'component', figmaName: 'Components/Navigation/Tabs', localName: 'Tabs', canvasApplicability: 'Publish a component set with active-tab variants and nested tab instances.' },
    autoLayout: layout('horizontal', '2px', '0px', 'End aligned on the active indicator', 'No wrap'),
    resizing: resize('hug', 'fixed', 'Content width', 'Parent or viewport width', '36px', '36px', 'visible'),
    exposedProperties: [property('active', 'Active tab', 'variant', null, 'active', undefined, true), property('label', 'Tab list label', 'text', 'Views', 'label', undefined, true), property('tabs', 'Tabs', 'slot', null, 'tabs', undefined, true), property('icon', 'Tab icon', 'instance-swap', null, 'Tab.icon')],
    nestedAssets: [nested('Tab list', 'primitive', true, 'Keyboard navigation container.', '<div role="tablist">'), nested('Tab', 'subcomponent', true, 'Repeatable label, optional icon, and indicator.', 'Tab data item'), nested('Tab panel', 'helper', true, 'Consumer-owned related content panel.', 'useTabPanelProps')],
    contentLimits: [limit('Tabs', 'Recommended two to five peer views', 'Use page navigation or another information architecture for larger sets.', 'All labels should remain visible without horizontal ambiguity.'), limit('Tab label', 'One or two words, maximum 20 characters', 'Do not truncate.', 'Short labels improve comparison and keyboard predictability.')],
    localization: localization(['Tab list label', 'Tab labels'], ['Visual order follows document direction.', 'Left and right arrow expectations must be tested for the supported browser behavior.'], ['Test all labels at twice English length.', 'Test panel relationships after translation.']),
    responsive: responsive('Intrinsic single row owned by its container.', ['Parent-selected narrow breakpoint'], ['Do not wrap tab rows.', 'Use horizontal scrolling only with an explicit overflow affordance, otherwise choose a different navigation pattern.']),
    limitations: limitations(['Prototype active variants do not validate roving focus or panel relationships.'], ['Consumers must pass the same stable id to Tabs and useTabPanelProps.']),
    governance: governance('src/components/Tabs.tsx', 'Design systems navigation primitive owner', 'Changes to tab order or activation require keyboard and information-architecture review.'),
  },
  dialog: {
    asset: { kind: 'component', figmaName: 'Components/Overlays/Dialog', localName: 'Dialog', canvasApplicability: 'Publish size variants with open state, title, description, and nested body content.' },
    autoLayout: layout('vertical', '0px between framed regions', '16px viewport inset; 20px mobile / 24px desktop header inset; 12px header block padding; close target pinned 6px from the top and logical end', 'Stretch', 'Content wraps'),
    resizing: resize('fill', 'hug', '280px', 'sm 384px; md 512px; lg 672px; xl 896px', 'Content controlled', 'Viewport minus 32px', 'auto'),
    exposedProperties: [property('open', 'Open', 'boolean', false, 'open', undefined, true), property('size', 'Size', 'variant', 'md', 'size', ['sm', 'md', 'lg', 'xl']), property('title', 'Title', 'text', null, 'title'), property('description', 'Description', 'text', null, 'description'), property('content', 'Content', 'slot', null, 'children', undefined, true)],
    nestedAssets: [nested('Backdrop', 'primitive', true, 'Full viewport modal overlay.', 'Internal fixed overlay'), nested('Panel', 'primitive', true, 'Focused dialog surface.', 'Headless UI DialogPanel'), nested('Header', 'subcomponent', false, 'Title, description, and close action.', 'Internal header'), nested('Body', 'slot', true, 'Focused task content.', 'children')],
    contentLimits: [limit('Title', 'One line preferred, maximum two lines', 'Wrap; do not truncate.', 'Users need a concise task name.'), limit('Description', 'Maximum three lines', 'Move long instructions into the body.', 'Header copy should orient, not explain the whole task.'), limit('Task scope', 'One focused task or decision', 'Move complex multi-section work to a page.', 'Dialogs interrupt the underlying workflow.')],
    localization: localization(['Title', 'Description', 'Body', 'Action labels'], ['Close action stays at logical end.', 'Content follows locale direction.'], ['Test twice-length titles.', 'Test at 200% zoom with keyboard-only dismissal.']),
    responsive: responsive('Width is capped by size and inset 16px from the viewport.', ['No internal breakpoint'], ['Panel shrinks to viewport width.', 'Body must remain reachable when content exceeds viewport height.']),
    limitations: limitations(['Figma overlays cannot validate focus trapping, restoration, Escape, or scroll lock.'], ['Always provide an accessible title through title or a correctly associated custom heading.']),
    governance: governance('src/components/Dialog.tsx', 'Design systems overlay primitive owner', 'Dismissal, focus, or size changes require overlay accessibility review.'),
  },
  modal: {
    asset: { kind: 'component', figmaName: 'Components/Overlays/Modal', localName: 'Modal family', canvasApplicability: 'Publish a composable overlay component with panel, header, body, and footer slots.' },
    autoLayout: layout('vertical', '0px between regions', '16px viewport inset; region padding owned by subcomponents; close target pinned 6px from the header top and logical end', 'Stretch', 'Region content wraps'),
    resizing: resize('fill', 'content-controlled', '280px', 'sm 384px; md 512px; lg 672px; xl 896px', 'Content controlled', 'Viewport minus 32px', 'auto'),
    exposedProperties: [property('open', 'Open', 'boolean', false, 'Conditional rendering of ModalOverlay'), property('size', 'Size', 'variant', 'lg', 'ModalPanel.size', ['sm', 'md', 'lg', 'xl']), property('closeOnBackdrop', 'Backdrop closes', 'boolean', true, 'ModalOverlay.closeOnBackdrop'), property('scroll', 'Scrollable body', 'boolean', true, 'ModalBody.scroll'), property('heading', 'Heading', 'text', 'Settings', 'ModalHeader.heading', undefined, true), property('description', 'Description', 'text', null, 'ModalHeader.description'), property('body', 'Body', 'slot', null, 'ModalBody children', undefined, true), property('footer', 'Footer', 'slot', null, 'ModalFooter children')],
    nestedAssets: [nested('ModalOverlay', 'subcomponent', true, 'Backdrop, semantics, dismissal, and focus boundary.', 'ModalOverlay'), nested('ModalPanel', 'subcomponent', true, 'Sized modal surface.', 'ModalPanel'), nested('ModalHeader', 'subcomponent', true, 'Heading, optional description, and close control.', 'ModalHeader'), nested('ModalBody', 'subcomponent', true, 'Primary scroll region.', 'ModalBody'), nested('ModalFooter', 'subcomponent', false, 'Action region.', 'ModalFooter')],
    contentLimits: [limit('Heading', 'One line preferred, maximum two lines', 'Wrap; never truncate.', 'The modal task should remain clear.'), limit('Footer actions', 'One primary and up to two secondary actions', 'Move tertiary actions into body content.', 'A contained decision needs a clear hierarchy.'), limit('Body', 'One focused workflow', 'Use a full page for broad or deeply nested tasks.', 'Modal interruption cost rises with complexity.')],
    localization: localization(['Heading', 'Description', 'Body', 'Action labels'], ['Header close action and footer alignment use logical sides.', 'Content follows locale direction.'], ['Test long action labels.', 'Test body overflow and 200% zoom.', 'Test nested directional form controls.']),
    responsive: responsive('Panel is viewport-constrained and body may scroll.', ['No internal breakpoint'], ['Maintain 16px viewport inset.', 'On product-defined small screens, a full-height presentation may be composed outside this primitive.']),
    limitations: limitations(['Figma nesting demonstrates structure but not portal, focus, inert background, or scroll-lock behavior.'], ['Consumers own whether the ModalOverlay is mounted; this family has no open prop itself.']),
    governance: governance('src/components/Modal.tsx', 'Design systems overlay primitive owner', 'Subcomponent contracts and dismissal changes require overlay accessibility review.'),
  },
  'confirm-dialog': {
    asset: { kind: 'component', figmaName: 'Components/Overlays/Confirm dialog', localName: 'ConfirmDialog', canvasApplicability: 'Publish standard, destructive, and loading variants with localized copy properties.' },
    autoLayout: layout('vertical', '0px regions; 12px between footer actions', '16px viewport inset; panel region padding', 'Stretch with actions aligned to logical end', 'Actions may wrap at narrow widths'),
    resizing: resize('fill', 'hug', '280px', '384px', 'Content controlled', 'Viewport minus 32px', 'auto'),
    exposedProperties: [property('open', 'Open', 'boolean', false, 'open', undefined, true), property('destructive', 'Destructive', 'boolean', false, 'destructive'), property('loading', 'Loading', 'boolean', false, 'loading'), property('title', 'Title', 'text', 'Confirm action?', 'title', undefined, true), property('description', 'Description', 'slot', null, 'description'), property('confirmLabel', 'Confirm label', 'text', 'Confirm', 'confirmLabel'), property('cancelLabel', 'Cancel label', 'text', 'Cancel', 'cancelLabel'), property('loadingLabel', 'Loading label', 'text', 'Working...', 'loadingLabel')],
    nestedAssets: [nested('Modal family', 'subcomponent', true, 'Alert dialog overlay, panel, header, body, and footer.', 'ModalOverlay and subcomponents'), nested('Cancel action', 'subcomponent', true, 'Secondary dismissal action.', 'Button'), nested('Confirm action', 'subcomponent', true, 'Consequential action and loading state.', 'Button')],
    contentLimits: [limit('Title', 'A direct question, maximum two lines', 'Wrap and revise if longer.', 'The exact decision must be obvious.'), limit('Description', 'One short paragraph describing consequence', 'Move detailed policy outside the dialog.', 'Users need enough context to decide without overload.'), limit('Action labels', 'Specific verbs, recommended maximum 24 characters', 'Stack actions if localization requires it.', 'Specific labels reduce confirmation errors.')],
    localization: localization(['Title', 'Description', 'Confirm, cancel, and loading labels'], ['Footer actions follow product locale conventions while preserving safe action hierarchy.', 'Directional icons, if added, mirror.'], ['Test long destructive verbs.', 'Test loading announcement and blocked dismissal.', 'Test 200% zoom.']),
    responsive: responsive('Small modal width with viewport inset.', ['Parent-selected narrow breakpoint'], ['Allow footer actions to stack full width in a product composition when labels no longer fit.', 'Do not reorder safe and destructive actions between widths.']),
    limitations: limitations(['Figma loading variants cannot validate blocked backdrop and Escape dismissal.'], ['The consumer owns asynchronous completion and must clear loading or close the dialog.']),
    governance: governance('src/components/ConfirmDialog.tsx', 'Design systems safety pattern owner', 'Destructive defaults or action ordering changes require safety, content, and accessibility review.'),
  },
  tooltip: {
    asset: { kind: 'component', figmaName: 'Components/Overlays/Tooltip', localName: 'Tooltip', canvasApplicability: 'Publish position and visibility variants attached to an example trigger.' },
    autoLayout: layout('horizontal', '0px', '6px 12px', 'Center', 'Text wraps up to maximum width'),
    resizing: resize('hug', 'hug', 'Content width', '240px', 'Content controlled', 'Content controlled', 'visible'),
    exposedProperties: [property('content', 'Content', 'text', 'Helpful information', 'content', undefined, true), property('position', 'Position', 'variant', 'top', 'position', ['top', 'bottom', 'left', 'right']), property('delay', 'Delay', 'number', 300, 'delay'), property('visible', 'Visible preview', 'boolean', true, 'Internal interaction state; no public prop'), property('trigger', 'Trigger', 'instance-swap', null, 'children', undefined, true)],
    nestedAssets: [nested('Trigger', 'slot', true, 'One focusable element that owns described-by state.', 'children'), nested('Tooltip bubble', 'primitive', true, 'Positioned supplemental text.', '<span role="tooltip">')],
    contentLimits: [limit('Content', 'One short sentence, maximum about 120 characters', 'Wrap up to 240px; move longer guidance into persistent UI.', 'Tooltips are supplemental and transient.'), limit('Children', 'Exactly one focusable trigger', 'Wrap compound visuals in one semantic control.', 'Focus and described-by must have one owner.')],
    localization: localization(['Content'], ['Position uses physical sides today; choose the appropriate side for the layout direction.', 'Text follows locale direction.'], ['Test 240px maximum width.', 'Test touch, keyboard, and pointer access with translated text.']),
    responsive: responsive('Bubble hugs content, portals to the document, flips when the opposite side fits, and clamps within an 8px viewport inset.', ['No internal breakpoint'], ['Preferred physical side remains consumer-selected.', 'Do not depend on tooltip access for essential mobile instructions.']),
    limitations: limitations(['Figma hover prototypes do not cover delayed focus, pointer travel, Escape, touch toggling, outside touch, viewport collision, or aria-describedby.'], ['Keep content supplemental, plain text, and non-interactive.']),
    governance: governance('src/components/Tooltip.tsx', 'Design systems overlay primitive owner', 'Timing or trigger-event changes require input-modality and accessibility testing.'),
  },
  'themed-hero-image': {
    asset: { kind: 'component', figmaName: 'Components/Media/Themed hero image', localName: 'ThemedHeroImage', canvasApplicability: 'Publish a frame-filling media component with dark and light image swaps and overlay variants.' },
    autoLayout: layout('overlay', '0px', '0px', 'Stretch to all frame edges', 'Layers overlap', ['Layer order is media, theme alternative, overlay, top fade, then bottom fade.']),
    resizing: resize('fill', 'fill', 'Parent controlled', 'Parent controlled', 'Parent controlled', 'Parent controlled', 'clip', ['The parent must be positioned and have an explicit or content-derived height.']),
    exposedProperties: [property('darkSrc', 'Dark image', 'instance-swap', null, 'darkSrc', undefined, true), property('lightSrc', 'Light image', 'instance-swap', null, 'lightSrc'), property('overlay', 'Overlay', 'variant', 'default', 'overlay', ['default', 'strong', 'soft', 'none']), property('fadeTop', 'Top fade', 'boolean', false, 'fadeTop'), property('fadeBottom', 'Bottom fade', 'boolean', false, 'fadeBottom'), property('blendLight', 'Light blend', 'boolean', false, 'blendLight'), property('objectPosition', 'Focal point', 'text', 'center', 'objectPosition')],
    nestedAssets: [nested('Dark media', 'slot', true, 'Required decorative image.', 'darkSrc'), nested('Light media', 'slot', false, 'Optional light-theme image.', 'lightSrc'), nested('Overlay', 'primitive', false, 'Theme token overlay treatment.', 'Internal overlay layer'), nested('Fades', 'primitive', false, 'Top and bottom content-legibility fades.', 'Internal fade layers')],
    contentLimits: [limit('Media role', 'Decorative hero imagery only', 'Use a semantic image component for meaningful content.', 'The implementation always uses empty alt text.'), limit('File weight', 'Use the smallest source that remains sharp at rendered sizes', 'Create responsive optimized assets.', 'Hero media has high performance impact.')],
    localization: localization([], ['Image framing must preserve important subjects for both directions.', 'Do not place baked-in text in the source image.'], ['Review focal points with right-to-left copy placement.', 'Test dark and light assets behind twice-length headings.']),
    responsive: responsive('Absolute fill with object-cover.', ['Use sizes to describe actual layout breakpoints'], ['Set a focal point that survives crop changes.', 'Parent owns aspect ratio and minimum content height.', 'Provide an accurate sizes value for image selection.']),
    limitations: limitations(['Figma fills do not validate Next Image loading, responsive source selection, or blend behavior.'], ['Always decorative; do not use for content that needs alternative text.']),
    governance: governance('src/components/ThemedHeroImage.tsx', 'Design systems media foundations owner', 'Overlay and blend changes require contrast review against representative hero copy.'),
  },
  theme: {
    asset: { kind: 'provider', figmaName: null, localName: 'ThemeProvider / useTheme / ThemeToggle', canvasApplicability: 'ThemeProvider and useTheme have no canvas geometry. Represent dark and light through Figma variable modes; document ThemeToggle separately as the visible consumer.' },
    autoLayout: noLayout('A context provider and hook do not have a rendered layout box.'),
    resizing: noResize('Provider and hook dimensions are not applicable; child layout remains unchanged.'),
    exposedProperties: [property('theme', 'Theme mode', 'variant', 'dark', 'ThemeProvider context and the dark or light Figma variable mode', ['dark', 'light']), property('accent', 'Accent scheme', 'variant', 'red', 'ThemeProvider context and active data-accent selector', ['red', 'green', 'blue', 'orange', 'yellow', 'purple', 'teal', 'pink', 'magenta']), property('children', 'Application subtree', 'slot', null, 'ThemeProvider children', undefined, true)],
    nestedAssets: [nested('Theme context', 'provider', true, 'Stores and exposes the active mode and accent scheme.', 'ThemeProvider and useTheme'), nested('Motion configuration', 'provider', true, 'Honors the user reduced-motion preference.', 'MotionConfig inside ThemeProvider'), nested('ThemeToggle', 'subcomponent', false, 'Ready-made visible mode switch.', 'ThemeToggle')],
    contentLimits: [limit('Provider instances', 'One provider at the application root', 'Remove nested ownership unless an isolated preview explicitly requires it.', 'Multiple competing global theme owners cause inconsistent persistence.')],
    localization: localization(['ThemeToggle accessible label and title'], ['Theme mode is direction-neutral.', 'Toggle placement follows the consuming layout.'], ['Test localized mode names in the toggle.', 'Test first render without stored preference.']),
    responsive: responsive('No provider geometry; all descendants retain their own responsive contracts.', ['Not applicable to provider'], ['ThemeToggle preserves its 44px square footprint wherever placed.']),
    limitations: limitations(['There is no Figma component instance for context behavior; use variable modes and a documented visible toggle.', 'Prototype variables do not reproduce localStorage persistence, accent persistence, or pre-hydration theme resolution.'], ['Wrap the app once and avoid component-owned global mode changes.', 'Keep destructive and feedback colors independent from the selected accent.'], ['Auto layout, padding, gap, resizing, and overflow do not apply to ThemeProvider or useTheme.']),
    governance: governance('src/components/ThemeProvider.tsx', 'Design systems theming foundations owner', 'Mode, accent, persistence, root selector, or styles/tokens.css changes require token, rendering, and accessibility review across every scheme and both themes.'),
  },
  cn: {
    asset: { kind: 'utility', figmaName: null, localName: 'cn', canvasApplicability: 'This class-merging function has no Figma or canvas representation.' },
    autoLayout: noLayout('A pure string utility emits no element and owns no auto-layout mechanics.'),
    resizing: noResize('A pure string utility has no width, height, constraints, or overflow.'),
    exposedProperties: [property('inputs', 'Class inputs', 'slot', null, 'Function arguments in precedence order', undefined, true), property('conditional', 'Include conditional input', 'boolean', true, 'Boolean expression passed as an input')],
    nestedAssets: [nested('tailwind-merge', 'helper', true, 'Resolves conflicting Tailwind utility classes.', 'Internal twMerge dependency')],
    contentLimits: [limit('Inputs', 'Class strings plus false, null, or undefined', 'Split complex style decisions into named variant functions.', 'The utility is for class composition, not component architecture.')],
    localization: localization([], ['Not applicable; class merging has no reading direction of its own.'], ['Verify logical-direction utilities when building localized components.']),
    responsive: responsive('Not applicable; emitted classes inherit Tailwind responsive behavior.', ['Not applicable to utility'], ['Responsive behavior is entirely determined by the input class strings.']),
    limitations: limitations(['No Figma asset should be created for this utility.'], ['Passing consumer className last is a policy choice; verify that it cannot remove required state or accessibility styles.'], ['Canvas geometry, auto layout, component properties, instance swaps, and prototype interactions are not applicable.']),
    governance: governance('src/lib/utils.ts', 'Design systems engineering foundations owner', 'Input types or merge-engine changes require a repository-wide class precedence audit.'),
  },
  'motion-helpers': {
    asset: { kind: 'helper', figmaName: null, localName: 'Motion helpers', canvasApplicability: 'Functions and timing constants have no reusable Figma component geometry. Document approved motion tokens and prototype examples instead.' },
    autoLayout: noLayout('Motion helper functions return Framer Motion props and emit no layout container.'),
    resizing: noResize('Motion helper functions own transforms and timing, not geometry constraints.'),
    exposedProperties: [property('delay', 'Delay', 'number', 0, 'fadeUpMotion or inViewFadeUpMotion delay argument'), property('offset', 'Vertical offset', 'number', 20, 'y argument or motionOffset token'), property('duration', 'Duration', 'number', 0.5, 'duration argument or motionDuration token'), property('distance', 'Hover distance', 'number', 2, 'subtleHoverMotion or borderHoverMotion distance argument')],
    nestedAssets: [nested('motionDuration', 'helper', true, 'Approved timing constants.', 'motionDuration'), nested('motionOffset', 'helper', true, 'Approved translation distances.', 'motionOffset'), nested('motionEase', 'helper', true, 'Approved easing curves.', 'motionEase'), nested('Motion element', 'slot', true, 'Consumer-owned Framer Motion element receiving helper output.', 'Spread returned props onto motion.*')],
    contentLimits: [limit('Concurrent effects', 'One primary entrance or hover effect per element', 'Remove competing transforms and ambient loops.', 'Motion should clarify hierarchy without becoming decoration.'), limit('Staggered collections', 'Keep total sequence short enough that the last item is not delayed from use', 'Reduce step or animate groups rather than every row.', 'Content must remain promptly available.')],
    localization: localization([], ['Transforms must not encode reading direction unless a product-specific helper explicitly does so.'], ['Test reduced motion.', 'Test layout in both directions to ensure transforms do not imply the wrong flow.']),
    responsive: responsive('No intrinsic geometry; the receiving element owns responsive behavior.', ['Not applicable to helper'], ['Reduce or remove spatial motion where small screens make displacement distracting.', 'Do not delay interactivity while animation completes.']),
    limitations: limitations(['Figma prototype easing and timing are reference approximations, not the canonical implementation.', 'Do not create a detached component for each animation helper.'], ['ThemeProvider is required for the shared reduced-motion policy.', 'Helper output may be overridden by later Framer Motion props.'], ['Auto layout, component resizing, text limits, and instance swapping are not owned by motion helpers.']),
    governance: governance('src/lib/motion.ts', 'Design systems motion foundations owner', 'Token or helper changes require reduced-motion review and regression checks on every consumer category.'),
  },
} satisfies Record<ComponentSpecId, ComponentConstructionSpecification>;

export { notApplicable as nonVisualCanvasMechanicsStatement };
