import type {
  AccessibilitySpecification,
  ComponentSpecDetails,
  ComponentSpecId,
  TestingContract,
} from './types';

const accessibility = (
  semantics: string,
  accessibleName: string,
  requirements: string[],
  announcements?: string[]
): AccessibilitySpecification => ({ semantics, accessibleName, requirements, announcements });

const testing = (
  unit: string[],
  interaction: string[],
  accessibilityChecks: string[],
  visual: string[]
): TestingContract => ({ unit, interaction, accessibility: accessibilityChecks, visual });

export const componentSpecDetails = {
  button: {
    slug: 'button',
    summary: 'The primary action primitive, with explicit hierarchy, size, and semantic-button behavior.',
    sourcePath: 'src/components/Button.tsx',
    packageExports: ['Button', 'buttonStyles', 'ButtonProps', 'ButtonSize', 'ButtonVariant'],
    anatomy: [
      { name: 'Container', description: 'Native action target carrying variant, size, and interaction styles.', required: true, semanticElement: 'button' },
      { name: 'Leading content', description: 'Optional decorative icon placed before the label.', required: false },
      { name: 'Label', description: 'Short verb phrase describing the result of activation.', required: true },
      { name: 'Trailing content', description: 'Optional icon communicating direction or external behavior.', required: false },
    ],
    visualSpec: {
      measurements: [
        { property: 'Corner radius', value: '6px', notes: 'Uses radius-md.' },
        { property: 'Content gap', value: '8px' },
        { property: 'Horizontal padding', value: '16 / 20 / 24 / 32px', notes: 'sm / md / lg / xl.' },
        { property: 'Vertical padding', value: '8 / 8 / 12 / 12px', notes: 'sm / md / lg / xl.' },
        { property: 'Icon-only target', value: '44 × 44px' },
      ],
      rules: ['Keep labels on one line.', 'Use the icon size for square icon-only controls; do not force an icon into text-button spacing.', 'Primary and destructive use distinct semantic action tokens; specific copy still communicates the consequence.'],
      responsiveBehavior: ['Use fullWidth only when the surrounding layout calls for a full-row action.', 'Stack competing actions at narrow widths in the consuming layout.'],
    },
    designTokens: [
      { token: '--color-action-primary / --color-action-primary-hover', purpose: 'Primary action background and hover.' },
      { token: '--color-action-destructive / --color-action-destructive-hover', purpose: 'Destructive action background and hover.' },
      { token: '--color-on-action', purpose: 'Foreground on filled actions.' },
      { token: '--color-control-border / --color-control-border-strong', purpose: 'Secondary, filter, and icon control boundaries.' },
      { token: '--color-focus', purpose: 'Global focus-visible outline.' },
      { token: '--motion-fast', purpose: 'Color transition duration.' },
      { token: '--radius-md', purpose: 'Container radius.' },
    ],
    stateDefinitions: [
      { name: 'default', trigger: 'Idle and enabled.', visual: 'Variant-specific fill, border, and text establish action hierarchy.', behavior: 'Activates on click, Enter, or Space.', accessibility: 'Native button semantics expose name and state.' },
      { name: 'hover', trigger: 'Pointer rests over an enabled button.', visual: 'Background, text, or border gains emphasis over 200ms.', behavior: 'No action until activation.' },
      { name: 'focus-visible', trigger: 'Keyboard focus enters the button.', visual: '2px focus-color outline with a 3px offset.', behavior: 'Remains the current tab stop.' },
      { name: 'disabled', trigger: 'disabled is true.', visual: '50% opacity and not-allowed cursor.', behavior: 'Native activation and focus are suppressed.', accessibility: 'Disabled state is exposed by the native element.' },
    ],
    keyboard: [
      { key: 'Enter', action: 'Activates the button.' },
      { key: 'Space', action: 'Activates the button.' },
      { key: 'Tab / Shift+Tab', action: 'Moves focus to or from an enabled button.' },
    ],
    accessibilitySpec: accessibility('Native <button>; buttonStyles is presentation-only when used on another element.', 'Visible text supplies the name. Icon-only buttons require aria-label.', ['Keep type="button" unless the control intentionally submits or resets a form.', 'Do not remove the focus-visible outline.', 'Mark decorative icons aria-hidden.', 'A disabled action must use the disabled attribute, not only visual opacity.']),
    implementation: {
      importStatement: "import { Button, buttonStyles } from '@ai-created/ui';",
      clientComponent: true,
      notes: ['Button forwards its HTMLButtonElement ref and all native button attributes.', 'Consumer className is merged last and can override default Tailwind utilities.', 'Use buttonStyles only when another semantic element genuinely needs the same appearance.'],
      recipes: [{ name: 'Submit action', description: 'Use a native submit type inside a form.', code: '<Button type="submit">Save changes</Button>' }],
    },
    guidance: { dos: ['Lead labels with a specific verb such as Save, Create, or Delete.', 'Use one clear primary action per decision area.'], donts: ['Do not use a button for navigation; use a link.', 'Do not rely on color alone to distinguish destructive meaning.'] },
    testing: testing(['Defaults to primary, md, and type button.', 'Forwards ref, className, disabled, and native attributes.'], ['Activates by pointer, Enter, and Space; disabled buttons do not activate.'], ['Has an accessible name and no axe violations in every variant.'], ['Snapshot every variant, size, disabled state, focus-visible state, and both themes.']),
    relatedComponents: ['confirm-dialog', 'tooltip', 'toggle'],
    controls: {
      variant: { type: 'select', label: 'Variant', defaultValue: 'primary', options: ['primary', 'secondary', 'destructive', 'ghost', 'filter', 'filter-active', 'icon'] },
      size: { type: 'select', label: 'Size', defaultValue: 'md', options: ['inline', 'sm', 'md', 'lg', 'xl', 'icon'] },
      label: { type: 'text', label: 'Label', defaultValue: 'Save changes' },
      disabled: { type: 'boolean', label: 'Disabled', defaultValue: false },
      fullWidth: { type: 'boolean', label: 'Full width', defaultValue: false },
    },
  },
  badge: {
    slug: 'badge',
    summary: 'A compact, non-interactive label for status, category, or short metadata.',
    sourcePath: 'src/components/Badge.tsx',
    packageExports: ['Badge', 'BadgeProps', 'BadgeVariant'],
    anatomy: [
      { name: 'Container', description: 'Inline pill that carries the semantic tone.', required: true, semanticElement: 'span' },
      { name: 'Label', description: 'Short status or category text.', required: true },
    ],
    visualSpec: { measurements: [{ property: 'Text size', value: '11px' }, { property: 'Horizontal padding', value: '8px' }, { property: 'Vertical padding', value: '2px' }, { property: 'Radius', value: '9999px' }, { property: 'Border', value: '1px' }], rules: ['Keep labels brief and non-wrapping.', 'Choose a tone that matches the status meaning, not decoration.'] },
    designTokens: [{ token: '--color-surface / --color-surface2', purpose: 'Neutral fills.' }, { token: '--color-border', purpose: 'Neutral border.' }, { token: '--color-success / warning / info / error', purpose: 'Semantic text.' }, { token: '--color-*-surface / --color-*-border', purpose: 'Semantic fill and border pairs.' }],
    stateDefinitions: [
      { name: 'default', trigger: 'Default variant.', visual: 'Surface2 fill with standard border and primary text.', behavior: 'Static metadata.' },
      { name: 'muted', trigger: 'Muted variant.', visual: 'Quieter surface and secondary text.', behavior: 'Static metadata.' },
      { name: 'success', trigger: 'Positive status.', visual: 'Success surface, border, and text.', behavior: 'Static metadata.' },
      { name: 'warning', trigger: 'Cautionary status.', visual: 'Warning surface, border, and text.', behavior: 'Static metadata.' },
      { name: 'error', trigger: 'Failure status.', visual: 'Error surface, border, and text.', behavior: 'Static metadata.' },
      { name: 'info', trigger: 'Informational status.', visual: 'Info surface, border, and text.', behavior: 'Static metadata.' },
    ],
    keyboard: [],
    accessibilitySpec: accessibility('Plain inline <span> with no implicit role.', 'Text content is read in surrounding context.', ['Write a meaningful label rather than encoding meaning only by color.', 'Do not add interaction to Badge; pair it with a real control when needed.']),
    implementation: { importStatement: "import { Badge } from '@ai-created/ui';", clientComponent: false, notes: ['Forwards a span ref and accepts native span attributes.', 'Use variant for semantic tone and className only for contextual layout.'] },
    guidance: { dos: ['Use one to three words.', 'Place close to the object or value being classified.'], donts: ['Do not use as a button or filter chip.', 'Do not put sentences or essential instructions in a badge.'] },
    testing: testing(['Renders a span and maps all six variants.', 'Forwards ref and native attributes.'], ['No interaction is expected.'], ['Text remains meaningful without color.'], ['Capture every tone in dark and light modes.']),
    relatedComponents: ['notice', 'surface'],
    controls: { variant: { type: 'select', label: 'Tone', defaultValue: 'default', options: ['default', 'muted', 'success', 'warning', 'error', 'info'] }, label: { type: 'text', label: 'Label', defaultValue: 'Ready' } },
  },
  surface: {
    slug: 'surface',
    summary: 'A themed structural container that groups related content without imposing semantics.',
    sourcePath: 'src/components/Surface.tsx',
    packageExports: ['Surface', 'surfaceStyles', 'SurfaceProps', 'SurfaceVariant', 'SurfacePadding', 'SurfaceInteraction'],
    anatomy: [{ name: 'Container', description: 'Bordered visual grouping root.', required: true, semanticElement: 'div' }, { name: 'Content slot', description: 'Free-form content that supplies the surface meaning.', required: true }],
    visualSpec: { measurements: [{ property: 'Radius', value: '6px' }, { property: 'Border', value: '1px' }, { property: 'Padding', value: '0 / 16 / 24 / 32 / 40px', notes: 'none / sm / md / lg / xl.' }, { property: 'Responsive padding', value: '32px, then 48px at md' }], rules: ['Pick a surface variant for structural or semantic meaning.', 'Interaction styling only supplies visual feedback; the consumer owns interactive semantics.'], responsiveBehavior: ['Responsive padding increases at the md breakpoint.', 'Width is controlled by the parent layout.'] },
    designTokens: [{ token: '--color-surface / --color-surface2 / --color-bg', purpose: 'Structural backgrounds.' }, { token: '--color-border / --color-border-strong', purpose: 'Default border and interaction emphasis.' }, { token: '--color-accent-border', purpose: 'Accent border.' }, { token: '--color-*-surface / --color-*-border', purpose: 'Semantic variants.' }, { token: '--radius-md', purpose: 'Corner radius.' }],
    stateDefinitions: [
      { name: 'default', trigger: 'No interaction.', visual: 'Stable themed fill and 1px border.', behavior: 'Pure layout container.' },
      { name: 'interactive group', trigger: 'A parent group is hovered or focus-visible.', visual: 'Border strengthens; accent surfaces use the accent border.', behavior: 'Feedback follows the parent control.' },
      { name: 'interactive within', trigger: 'The surface is hovered or contains focus.', visual: 'Border strengthens over 200ms.', behavior: 'Does not become keyboard interactive by itself.' },
    ],
    keyboard: [],
    accessibilitySpec: accessibility('Default element is a non-semantic <div>. surfaceStyles can style another semantic root.', 'The surface has no name by default.', ['Add a heading, region label, list semantics, or interactive wrapper when content needs structure.', 'Never imply clickability through interaction styling without a keyboard-operable element.']),
    implementation: { importStatement: "import { Surface, surfaceStyles } from '@ai-created/ui';", clientComponent: false, notes: ['Surface forwards a div ref and native HTML attributes.', 'Use surfaceStyles to apply the same visual contract to a semantic article, section, or link.'] },
    guidance: { dos: ['Use consistent padding for peer surfaces.', 'Choose inset when the content should visually recede.'], donts: ['Do not nest multiple bordered surfaces without a clear hierarchy.', 'Do not add group interaction to a non-interactive card.'] },
    testing: testing(['Maps every variant, padding, and interaction value.', 'Consumer className overrides default utilities.'], ['Group and focus-within borders respond to their documented triggers.'], ['Semantic wrappers retain their roles and names.'], ['Cover all variants plus interaction borders in both themes.']),
    relatedComponents: ['notice', 'empty-state', 'modal'],
    controls: { variant: { type: 'select', label: 'Variant', defaultValue: 'default', options: ['default', 'muted', 'accent', 'inset', 'success', 'warning', 'info', 'error'] }, padding: { type: 'select', label: 'Padding', defaultValue: 'none', options: ['none', 'sm', 'md', 'lg', 'xl', 'responsive'] }, interaction: { type: 'select', label: 'Interaction', defaultValue: 'none', options: ['none', 'group', 'within'] } },
  },
  notice: {
    slug: 'notice',
    summary: 'An inline live-region message for informational, positive, cautionary, or error feedback.',
    sourcePath: 'src/components/Notice.tsx',
    packageExports: ['Notice', 'NoticeProps', 'NoticeVariant'],
    anatomy: [{ name: 'Surface', description: 'Semantic-tone container and live region.', required: true, semanticElement: 'div' }, { name: 'Status icon', description: 'Decorative tone reinforcement.', required: false }, { name: 'Title', description: 'Optional concise message heading.', required: false }, { name: 'Body', description: 'Supporting explanation or recovery guidance.', required: false }],
    visualSpec: { measurements: [{ property: 'Padding', value: '24px' }, { property: 'Content gap', value: '16px' }, { property: 'Icon', value: '16 × 16px' }, { property: 'Radius', value: '6px' }, { property: 'Title/body gap', value: '8px' }], rules: ['Align icon and content to the top unless centered is intentionally used.', 'Use semantic surface, border, text, and icon color as a coordinated set.'] },
    designTokens: [{ token: '--color-*-surface', purpose: 'Tone background.' }, { token: '--color-*-border', purpose: 'Tone border.' }, { token: '--color-info / success / warning / error', purpose: 'Title and icon.' }, { token: '--color-text2', purpose: 'Body copy.' }],
    stateDefinitions: [
      { name: 'default', trigger: 'Neutral message.', visual: 'Default Surface with no status icon.', behavior: 'Polite status announcement.' },
      { name: 'info', trigger: 'Informational message.', visual: 'Blue semantic treatment and info icon.', behavior: 'Polite status announcement.' },
      { name: 'success', trigger: 'Successful outcome.', visual: 'Green semantic treatment and check icon.', behavior: 'Polite status announcement.' },
      { name: 'warning', trigger: 'Caution or required review.', visual: 'Yellow semantic treatment and warning icon.', behavior: 'Polite status announcement.' },
      { name: 'error', trigger: 'Failed outcome.', visual: 'Red semantic treatment and error icon.', behavior: 'Assertive alert announcement.', accessibility: 'Defaults to role alert and aria-live assertive.' },
    ],
    keyboard: [],
    accessibilitySpec: accessibility('role=status by default; error uses role=alert. Both are overridable.', 'Title and body text form the announcement.', ['Keep icons decorative.', 'Avoid inserting a status region before its content is ready if it should be announced as a change.', 'Use error only for information that merits an assertive interruption.'], ['Default, info, success, and warning use polite live announcements.', 'Error uses an assertive announcement.']),
    implementation: { importStatement: "import { Notice } from '@ai-created/ui';", clientComponent: false, notes: ['The role and aria-live defaults are derived from variant.', 'centered and hideIcon change presentation only.', 'Use ErrorReport when technical details need disclosure and copying.'] },
    guidance: { dos: ['Explain what happened and the next useful step.', 'Place the notice near the content it affects.'], donts: ['Do not use for ephemeral toast positioning.', 'Do not make every informational note assertive.'] },
    testing: testing(['Derives Surface variant, role, and aria-live correctly.', 'Honors explicit role and aria-live overrides.'], ['A newly rendered error is announced; centered and hidden-icon options preserve content.'], ['Icons are hidden and live-region semantics match severity.'], ['Capture every tone, title/body combination, centered treatment, and both themes.']),
    relatedComponents: ['error-report', 'badge', 'surface'],
    controls: { variant: { type: 'select', label: 'Tone', defaultValue: 'default', options: ['default', 'info', 'success', 'warning', 'error'] }, title: { type: 'text', label: 'Title', defaultValue: 'Review required' }, centered: { type: 'boolean', label: 'Centered', defaultValue: false }, hideIcon: { type: 'boolean', label: 'Hide icon', defaultValue: false } },
  },
  skeleton: {
    slug: 'skeleton',
    summary: 'A decorative loading placeholder that reserves the final content footprint.',
    sourcePath: 'src/components/Skeleton.tsx',
    packageExports: ['Skeleton', 'SkeletonProps'],
    anatomy: [{ name: 'Placeholder block', description: 'Consumer-sized pulse surface matching future content.', required: true, semanticElement: 'div' }],
    visualSpec: { measurements: [{ property: 'Radius', value: '6px by default' }, { property: 'Width and height', value: 'Consumer-defined' }, { property: 'Animation', value: 'Tailwind pulse; disabled for reduced motion' }], rules: ['Match the dimensions and shape of the content being loaded.', 'Preserve stable layout between placeholder and resolved content.'] },
    designTokens: [{ token: '--color-surface2', purpose: 'Placeholder fill.' }, { token: '--radius-md', purpose: 'Default radius.' }],
    stateDefinitions: [{ name: 'loading', trigger: 'Content is pending.', visual: 'Surface2 block pulses unless reduced motion is requested.', behavior: 'Reserves layout only.', accessibility: 'Hidden from the accessibility tree.' }],
    keyboard: [],
    accessibilitySpec: accessibility('Decorative <div aria-hidden="true">.', 'No accessible name; the surrounding loading region owns status.', ['Provide a separate loading announcement when users need one.', 'Do not put focusable content inside the skeleton.', 'Respect reduced-motion behavior.']),
    implementation: { importStatement: "import { Skeleton } from '@ai-created/ui';", clientComponent: false, notes: ['Set dimensions and alternate shapes with className.', 'The placeholder is always aria-hidden and forwards div attributes.'] },
    guidance: { dos: ['Approximate the final content structure.', 'Use a small group of meaningful shapes.'], donts: ['Do not use arbitrary decorative skeleton grids.', 'Do not leave skeletons visible after loading fails.'] },
    testing: testing(['Forwards className, ref, and div attributes.', 'Always emits aria-hidden true.'], ['Replaced content does not cause large layout shift.'], ['Loading status exists outside the hidden placeholder when required.'], ['Compare content and skeleton dimensions; verify reduced-motion rendering.']),
    relatedComponents: ['empty-state', 'notice'],
    controls: { shape: { type: 'select', label: 'Shape', defaultValue: 'content', options: ['content', 'text', 'avatar'] }, width: { type: 'select', label: 'Width', defaultValue: 'full', options: ['short', 'medium', 'full'] } },
  },
  'empty-state': {
    slug: 'empty-state',
    summary: 'A calm, explanatory collection state with an optional next-step action.',
    sourcePath: 'src/components/EmptyState.tsx',
    packageExports: ['EmptyState', 'EmptyStateProps'],
    anatomy: [{ name: 'Surface', description: 'Muted responsive container.', required: true, semanticElement: 'div' }, { name: 'Icon', description: 'Optional decorative context cue.', required: false }, { name: 'Title', description: 'Explains the empty condition.', required: true }, { name: 'Description', description: 'Optional reason or next-step guidance.', required: false }, { name: 'Action area', description: 'Optional children, usually one Button.', required: false }],
    visualSpec: { measurements: [{ property: 'Padding', value: '32px mobile / 48px md+' }, { property: 'Icon', value: '48 × 48px' }, { property: 'Icon bottom margin', value: '16px' }, { property: 'Title/description gap', value: '8px' }, { property: 'Action top margin', value: '24px' }, { property: 'Copy width with icon', value: 'max-width 448px' }], rules: ['Center all content.', 'Keep actions subordinate to the explanation.', 'Use muted Surface styling rather than error styling.'] },
    designTokens: [{ token: '--color-surface2', purpose: 'Muted Surface fill.' }, { token: '--color-border', purpose: 'Container border.' }, { token: '--color-text2', purpose: 'Title.' }, { token: '--color-text3', purpose: 'Icon and description.' }],
    stateDefinitions: [{ name: 'empty', trigger: 'A successfully loaded collection has no items.', visual: 'Centered optional icon, copy, and action on a muted surface.', behavior: 'Action follows its own component behavior.' }],
    keyboard: [{ key: 'Tab', action: 'Moves to actions supplied as children.', condition: 'Only when an action is present.' }],
    accessibilitySpec: accessibility('Non-semantic Surface container; child action preserves its own semantics.', 'The visible title names the state in reading order.', ['Use a clear title that distinguishes empty from loading or failure.', 'Icons are decorative.', 'Supply a heading element through composition when the surrounding page hierarchy requires one.']),
    implementation: { importStatement: "import { EmptyState, Button } from '@ai-created/ui';", clientComponent: false, notes: ['Accepts all div attributes and forwards the container ref through Surface.', 'The icon prop accepts a Lucide icon component and marks it decorative.'] },
    guidance: { dos: ['Explain why the view is empty when it may be surprising.', 'Offer one concrete next step when the user can resolve it.'], donts: ['Do not show during loading.', 'Do not use upbeat copy for data loss or a failure.'] },
    testing: testing(['Renders required title and optional icon, description, and children.', 'Forwards Surface div attributes.'], ['Optional action remains keyboard operable.'], ['Reading order is icon-hidden, title, description, action.'], ['Capture with/without icon and action at mobile and desktop padding.']),
    relatedComponents: ['skeleton', 'notice', 'button', 'surface'],
    controls: { title: { type: 'text', label: 'Title', defaultValue: 'No projects yet' }, description: { type: 'text', label: 'Description', defaultValue: 'Create one to get started.' } },
  },
  'error-report': {
    slug: 'error-report',
    summary: 'An error notice with optional expandable, copyable diagnostics for support workflows.',
    sourcePath: 'src/components/ErrorReport.tsx',
    packageExports: ['ErrorReport', 'ErrorReportProps'],
    anatomy: [{ name: 'Error notice', description: 'Assertive error container and title.', required: true }, { name: 'Message', description: 'User-facing failure summary.', required: true }, { name: 'Disclosure', description: 'Optional Debug info toggle.', required: false, semanticElement: 'button' }, { name: 'Diagnostic block', description: 'Expanded preformatted details, timestamp, and URL.', required: false, semanticElement: 'pre' }, { name: 'Copy action', description: 'Copies the assembled diagnostics.', required: false, semanticElement: 'button' }],
    visualSpec: { measurements: [{ property: 'Notice padding', value: '24px' }, { property: 'Internal vertical gap', value: '8px' }, { property: 'Diagnostic padding', value: '12px' }, { property: 'Disclosure icon', value: '12 × 12px' }], rules: ['Keep the user-facing message readable without opening diagnostics.', 'Prevent long diagnostic lines from breaking the containing layout.'] },
    designTokens: [{ token: '--color-error / --color-error-surface / --color-error-border', purpose: 'Error Notice treatment.' }, { token: '--color-surface2', purpose: 'Diagnostic code block.' }, { token: '--color-text2 / --color-text3', purpose: 'Message and low-emphasis controls.' }],
    stateDefinitions: [
      { name: 'collapsed', trigger: 'Details exist but disclosure is closed.', visual: 'Message and Debug info disclosure are visible.', behavior: 'Technical details are not mounted.', accessibility: 'aria-expanded is false and aria-controls points to the details id.' },
      { name: 'expanded', trigger: 'Disclosure is activated.', visual: 'Diagnostic pre block and copy action appear.', behavior: 'Details include error, timestamp, and current path.', accessibility: 'aria-expanded is true.' },
      { name: 'copied', trigger: 'Clipboard write resolves.', visual: 'Copy action becomes Copied for two seconds.', behavior: 'Diagnostic string is on the clipboard.' },
      { name: 'copy failed', trigger: 'Clipboard write rejects or is unavailable.', visual: 'Copy action becomes Copy failed for two seconds.', behavior: 'The rejection is handled without an unhandled promise and the user may retry.', accessibility: 'The polite live status announces the failure.' },
    ],
    keyboard: [{ key: 'Enter / Space', action: 'Toggles diagnostic disclosure when focused.' }, { key: 'Enter / Space', action: 'Copies diagnostics from the copy button.' }, { key: 'Tab', action: 'Moves through disclosure and copy action when present.' }],
    accessibilitySpec: accessibility('Composes role=alert Notice plus native disclosure and copy buttons.', 'The Notice title and message identify the error; buttons have visible names.', ['Never include credentials, tokens, personal data, or full query strings in details.', 'Preserve aria-expanded and aria-controls on the disclosure.', 'Copy success and failure feedback must remain visible long enough to perceive.'], ['The error Notice is assertively announced.', 'Clipboard success or failure is announced through a polite live status.']),
    implementation: { importStatement: "import { ErrorReport } from '@ai-created/ui';", clientComponent: true, notes: ['details controls whether the disclosure and copy action exist.', 'timestamp should be supplied for deterministic reports; otherwise it is created when debugInfo renders.', 'The URL is limited to origin and pathname.', 'Clipboard rejection is handled and the feedback timer is cleared on replacement and unmount.'] },
    guidance: { dos: ['Write the message for the user before adding technical detail.', 'Sanitize all detail strings at the error boundary.'], donts: ['Do not pass stack traces containing secrets.', 'Do not use for field-level validation.'] },
    testing: testing(['Assembles diagnostic text with optional details and timestamp.', 'Resets copy success or failure feedback after two seconds.'], ['Disclosure toggles; clipboard resolution and rejection both produce the expected status.'], ['Alert, disclosure relationship, button names, focus order, and polite clipboard status are valid.'], ['Capture collapsed, expanded, copied, copy-failed, long-details, and both themes.']),
    relatedComponents: ['notice', 'button'],
    controls: { title: { type: 'text', label: 'Title', defaultValue: 'Something went wrong' }, message: { type: 'text', label: 'Message', defaultValue: 'Unable to load projects.' }, details: { type: 'text', label: 'Details', defaultValue: 'Request timed out.' } },
  },
  field: {
    slug: 'field',
    summary: 'Composable labels, hints, text controls, and style helpers for consistent form fields.',
    sourcePath: 'src/components/Field.tsx',
    packageExports: ['FieldGroup', 'FieldLabel', 'FieldLegend', 'FieldHint', 'TextInput', 'TextArea', 'fieldGroupStyles', 'fieldLabelStyles', 'fieldLegendStyles', 'fieldHintStyles', 'inputStyles'],
    anatomy: [{ name: 'Field group', description: 'Layout wrapper for one logical field.', required: true, semanticElement: 'div' }, { name: 'Label', description: 'Visible name associated to the control.', required: true, semanticElement: 'label' }, { name: 'Control', description: 'Native input or textarea.', required: true, semanticElement: 'input / textarea' }, { name: 'Hint', description: 'Optional help or validation message associated by id.', required: false, semanticElement: 'p' }, { name: 'Visual legend', description: 'Optional uppercase group caption; not a semantic legend.', required: false, semanticElement: 'span' }],
    visualSpec: { measurements: [{ property: 'FieldGroup sibling gap', value: '8px' }, { property: 'Label, legend, and hint exterior margin', value: '0px' }, { property: 'Input padding', value: '16px horizontal / 12px vertical' }, { property: 'Input radius', value: '6px' }, { property: 'Input border', value: '1px' }], rules: ['FieldGroup is the single owner of vertical spacing between its label, control, and optional hint.', 'Keep labels persistently visible; placeholders are examples, not labels.', 'Apply validation meaning and relationships in consuming code.', 'TextArea disables manual resizing by default.'] },
    designTokens: [{ token: '--color-surface2', purpose: 'Control background.' }, { token: '--color-control-border / --color-control-border-strong', purpose: 'Contrast-safe default and hover boundaries.' }, { token: '--color-accent', purpose: 'Focused border.' }, { token: '--color-text / --color-text2 / --color-text3', purpose: 'Value, label/help, and placeholder hierarchy.' }, { token: '--radius-md', purpose: 'Control radius.' }],
    stateDefinitions: [
      { name: 'default', trigger: 'Idle enabled field.', visual: 'Surface2 fill, standard border, primary value, secondary label.', behavior: 'Native text editing.' },
      { name: 'focus-visible', trigger: 'Keyboard focus enters the control.', visual: 'Global focus outline plus accent border.', behavior: 'Accepts keyboard input.' },
      { name: 'disabled', trigger: 'Native disabled is set.', visual: '50% opacity and not-allowed cursor.', behavior: 'Editing and focus are suppressed.' },
      { name: 'invalid', trigger: 'Consumer sets aria-invalid and error styling/content.', visual: 'Consumer must add a clear error treatment.', behavior: 'Validation message explains correction.', accessibility: 'aria-invalid and aria-describedby connect the error.' },
    ],
    keyboard: [{ key: 'Tab / Shift+Tab', action: 'Moves focus into or out of the control.' }, { key: 'Standard text editing keys', action: 'Edit, select, undo, and navigate text according to the native platform.' }],
    accessibilitySpec: accessibility('Native label, input, textarea, and paragraph primitives; FieldGroup and FieldLegend are presentation-only.', 'Associate FieldLabel with the control using htmlFor/id, or nest the control.', ['Connect FieldHint and validation errors with aria-describedby.', 'Set aria-invalid when validation fails.', 'Use a real fieldset and legend for grouped choices; FieldLegend is only a styled span.', 'Preserve native autocomplete, inputMode, type, and name attributes.']),
    implementation: { importStatement: "import { FieldGroup, FieldLabel, FieldHint, TextInput, TextArea } from '@ai-created/ui';", clientComponent: true, notes: ['Every primitive forwards its native ref and attributes.', 'FieldGroup owns the 8px sibling gap; FieldLabel, FieldLegend, and FieldHint add no exterior margin.', 'Style helpers support custom controls inside the same group spacing contract without duplicating class contracts.', 'The family does not generate ids or accessibility relationships for the consumer.'] },
    guidance: { dos: ['Use concise noun-phrase labels and useful format hints.', 'Show validation next to the field and explain resolution.'], donts: ['Do not use placeholder text as the only label.', 'Do not use FieldLegend as a substitute for semantic fieldset/legend.'] },
    testing: testing(['Each primitive forwards refs and native props.', 'Style helpers merge consumer overrides last and only FieldGroup supplies exterior sibling spacing.'], ['Label click focuses the associated control and typing updates the form model.'], ['Label, description, validation, autocomplete, and disabled semantics are correct at responsive widths and 200% text zoom.'], ['Measure label-to-input, label-to-textarea, and control-to-hint gaps; assert equal-height Field and Dropdown labels produce equal control tops; capture wrapped labels, no-hint, invalid, disabled, responsive, and both-theme states.']),
    relatedComponents: ['checkbox', 'radio-group', 'slider', 'dropdown'],
    controls: { control: { type: 'select', label: 'Control', defaultValue: 'input', options: ['input', 'textarea'] }, label: { type: 'text', label: 'Label', defaultValue: 'Email' }, hint: { type: 'text', label: 'Hint', defaultValue: 'We will never share it.' }, disabled: { type: 'boolean', label: 'Disabled', defaultValue: false } },
  },
  checkbox: {
    slug: 'checkbox',
    summary: 'A controlled native checkbox for one independent boolean choice.',
    sourcePath: 'src/components/Checkbox.tsx',
    packageExports: ['Checkbox', 'CheckboxProps'],
    anatomy: [{ name: 'Label wrapper', description: 'Full clickable label and layout root.', required: true, semanticElement: 'label' }, { name: 'Native input', description: 'Visually hidden checkbox owning state and semantics.', required: true, semanticElement: 'input[type=checkbox]' }, { name: 'Visual box', description: '16px state indicator and focus target proxy.', required: true }, { name: 'Check icon', description: 'Decorative selected mark.', required: false }, { name: 'Label text', description: 'Visible accessible name.', required: true }],
    visualSpec: { measurements: [{ property: 'Indicator', value: '16 × 16px' }, { property: 'Indicator radius', value: '4px' }, { property: 'Content gap', value: '10px' }, { property: 'Check icon', value: '12 × 12px, 3px stroke' }, { property: 'Label text', value: '12px' }], rules: ['The whole label is clickable.', 'Keep label adjacent to the indicator.', 'Use checkbox only for choices that can stand independently.'] },
    designTokens: [{ token: '--color-action-primary', purpose: 'Checked fill and border.' }, { token: '--color-on-action', purpose: 'Checked mark.' }, { token: '--color-control-border / --color-control-border-strong', purpose: 'Unchecked and hover boundary.' }, { token: '--color-focus', purpose: 'Peer focus-visible outline.' }, { token: '--color-text2', purpose: 'Label.' }, { token: '--motion-fast', purpose: 'State transition.' }],
    stateDefinitions: [
      { name: 'checked', trigger: 'checked is true.', visual: 'Solid action fill with white check.', behavior: 'Activation requests false through onChange.', accessibility: 'Native checked state is exposed.' },
      { name: 'unchecked', trigger: 'checked is false.', visual: 'Transparent box with strong border.', behavior: 'Activation requests true through onChange.' },
      { name: 'disabled', trigger: 'disabled is true.', visual: 'Indicator and label use 50% opacity; cursor is not-allowed.', behavior: 'Native input cannot focus or change.' },
      { name: 'focus-visible', trigger: 'Keyboard focus reaches the hidden input.', visual: 'Visual box receives 2px outline with 3px offset.', behavior: 'Space toggles the input.' },
    ],
    keyboard: [{ key: 'Space', action: 'Toggles the focused checkbox.' }, { key: 'Tab / Shift+Tab', action: 'Moves focus to or from an enabled checkbox.' }],
    accessibilitySpec: accessibility('Native checkbox nested in an associated label.', 'Required visible label string supplies the name.', ['State is controlled; update checked in onChange.', 'Do not hide or replace the visible label with color/icon only.', 'Use disabled for unavailable choices.']),
    implementation: { importStatement: "import { Checkbox } from '@ai-created/ui';", clientComponent: false, notes: ['A generated id connects the label and input.', 'The component forwards the HTMLInputElement ref.', 'onChange receives the next boolean value rather than a DOM event.'] },
    guidance: { dos: ['Use affirmative labels that make sense when checked.', 'Group related checkboxes under a visible group heading.'], donts: ['Do not use for mutually exclusive options.', 'Do not require users to infer the unchecked meaning from a negative label.'] },
    testing: testing(['Reflects controlled checked and disabled props.', 'Calls onChange once with the next value.'], ['Label click and Space toggle; disabled state does not.'], ['Native checkbox has visible associated label and focus indicator.'], ['Capture checked/unchecked, hover, focus, disabled, long label, and both themes.']),
    relatedComponents: ['radio-group', 'toggle', 'field'],
    controls: { checked: { type: 'boolean', label: 'Checked', defaultValue: false }, disabled: { type: 'boolean', label: 'Disabled', defaultValue: false }, label: { type: 'text', label: 'Label', defaultValue: 'I agree' } },
  },
  'radio-group': {
    slug: 'radio-group',
    summary: 'A controlled fieldset for selecting exactly one value from a small, visible option set.',
    sourcePath: 'src/components/RadioGroup.tsx',
    packageExports: ['RadioGroup', 'RadioGroupProps', 'RadioOption'],
    anatomy: [{ name: 'Fieldset', description: 'Semantic group and disabled boundary.', required: true, semanticElement: 'fieldset' }, { name: 'Legend', description: 'Persistent group name.', required: true, semanticElement: 'legend' }, { name: 'Native radio', description: 'Visually hidden option input.', required: true, semanticElement: 'input[type=radio]' }, { name: 'Indicator', description: '16px circular selection mark.', required: true }, { name: 'Option label', description: 'Visible name and 44px minimum row target.', required: true, semanticElement: 'label' }],
    visualSpec: { measurements: [{ property: 'Option row minimum height', value: '44px' }, { property: 'Indicator', value: '16 × 16px' }, { property: 'Selected dot', value: '9.6 × 9.6px' }, { property: 'Indicator/label gap', value: '10px' }, { property: 'Vertical option gap', value: '10px' }, { property: 'Horizontal option gap', value: '16px' }], rules: ['Show all choices when the set is short enough.', 'Use vertical orientation when labels vary in length.', 'Stable values belong in domain data; labels may change.'] },
    designTokens: [{ token: '--color-action-primary', purpose: 'Selected indicator.' }, { token: '--color-on-action', purpose: 'Selected inner mark.' }, { token: '--color-control-border / --color-control-border-strong', purpose: 'Unselected and hover boundary.' }, { token: '--color-focus', purpose: 'Peer focus outline.' }, { token: '--color-text2', purpose: 'Legend and option labels.' }],
    stateDefinitions: [
      { name: 'selected', trigger: 'Option value equals group value.', visual: 'Solid action circle with white inner dot.', behavior: 'This option is the group tab stop.', accessibility: 'Native checked state is exposed.' },
      { name: 'unselected', trigger: 'Option value differs.', visual: 'Transparent indicator with strong border.', behavior: 'Activation selects this value.' },
      { name: 'disabled', trigger: 'Group or option is disabled.', visual: '50% opacity and not-allowed cursor.', behavior: 'Option cannot receive focus or selection.' },
      { name: 'focus-visible', trigger: 'Keyboard focus reaches a radio.', visual: '2px focus outline with 3px offset on indicator.', behavior: 'Native radio navigation remains active.' },
    ],
    keyboard: [{ key: 'Arrow keys', action: 'Moves selection and focus among enabled native radios.' }, { key: 'Space', action: 'Selects the focused option.' }, { key: 'Tab', action: 'Enters or leaves the radio group as one stop.' }],
    accessibilitySpec: accessibility('Native fieldset, legend, and radio inputs; an additional radiogroup wrapper carries aria-label.', 'The required legend names the group; each visible option label names its radio.', ['Provide at least two meaningful options.', 'Do not duplicate option values.', 'Disabled options must remain understandable in context.', 'Keep name stable when integrating with native form submission.']),
    implementation: { importStatement: "import { RadioGroup, type RadioOption } from '@ai-created/ui';", clientComponent: false, notes: ['Generic string values preserve a narrow domain union.', 'The fieldset ref is forwarded.', 'onChange receives the chosen value directly.'] },
    guidance: { dos: ['Use for mutually exclusive peer choices.', 'Order choices predictably and keep labels parallel.'], donts: ['Do not use for independent booleans.', 'Do not use for very large or searchable datasets.'] },
    testing: testing(['Renders options, generated ids/name, orientation, and disabled merging.', 'Calls onChange with the activated value.'], ['Pointer, Space, and arrow behavior select enabled options only.'], ['Fieldset/legend/input/label relationships and group name are valid.'], ['Capture orientations, selection, focus, group disabled, option disabled, and both themes.']),
    relatedComponents: ['checkbox', 'dropdown', 'field'],
    controls: { value: { type: 'select', label: 'Selected', defaultValue: 'design', options: ['design', 'engineering', 'research'] }, orientation: { type: 'select', label: 'Orientation', defaultValue: 'vertical', options: ['vertical', 'horizontal'] }, disabled: { type: 'boolean', label: 'Disabled', defaultValue: false } },
  },
  toggle: {
    slug: 'toggle',
    summary: 'A controlled switch for an immediate on/off setting.',
    sourcePath: 'src/components/Toggle.tsx',
    packageExports: ['Toggle', 'ToggleProps'],
    anatomy: [{ name: 'Switch button', description: '44px-minimum interactive root.', required: true, semanticElement: 'button[role=switch]' }, { name: 'Track', description: '40 × 24px visual state container and focus proxy.', required: true }, { name: 'Thumb', description: '16px moving state marker.', required: true }, { name: 'Label', description: 'Visible switch name.', required: true }],
    visualSpec: { measurements: [{ property: 'Target minimum height', value: '44px' }, { property: 'Track', value: '40 × 24px' }, { property: 'Thumb', value: '16 × 16px' }, { property: 'Thumb position', value: '3px off / 25px on' }, { property: 'Label gap', value: '10px' }], rules: ['Use on for the enabled/active meaning.', 'The setting takes effect on activation; use a checkbox or form action when changes are deferred.'] },
    designTokens: [{ token: '--color-action-primary', purpose: 'On track fill and border.' }, { token: '--color-on-action', purpose: 'Thumb fill.' }, { token: '--color-surface2', purpose: 'Off track fill.' }, { token: '--color-control-border / --color-control-border-strong', purpose: 'Off track and hover boundary.' }, { token: '--color-focus', purpose: 'Track focus outline.' }, { token: '--motion-fast', purpose: 'Track color and thumb movement.' }],
    stateDefinitions: [
      { name: 'on', trigger: 'checked is true.', visual: 'Solid track; thumb translated right.', behavior: 'Activation requests false.', accessibility: 'aria-checked true.' },
      { name: 'off', trigger: 'checked is false.', visual: 'Surface2 track; thumb at left.', behavior: 'Activation requests true.', accessibility: 'aria-checked false.' },
      { name: 'disabled', trigger: 'disabled is true.', visual: 'Track and label at 50% opacity.', behavior: 'Native button cannot focus or activate.' },
      { name: 'focus-visible', trigger: 'Keyboard focus reaches the switch.', visual: '2px focus outline with 3px offset on track.', behavior: 'Space or Enter toggles.' },
    ],
    keyboard: [{ key: 'Enter / Space', action: 'Toggles the switch.' }, { key: 'Tab / Shift+Tab', action: 'Moves focus to or from an enabled switch.' }],
    accessibilitySpec: accessibility('Native button with role=switch and aria-checked.', 'Required visible label is included in the button name.', ['Keep label text stable between states.', 'State must be controlled and updated from onChange.', 'Do not announce on/off again in the label; switch semantics already expose it.']),
    implementation: { importStatement: "import { Toggle } from '@ai-created/ui';", clientComponent: false, notes: ['Forwards an HTMLButtonElement ref.', 'onChange receives the next boolean immediately.', 'The visual track and thumb are aria-hidden.'] },
    guidance: { dos: ['Use for settings applied immediately.', 'Phrase labels as the feature being enabled.'], donts: ['Do not use for commands such as Send or Save.', 'Do not use if changing the value requires a separate submit step.'] },
    testing: testing(['Reflects checked and disabled state and calls onChange with the inverse.', 'Always uses type button.'], ['Pointer, Enter, and Space toggle once; disabled does not.'], ['Role, name, aria-checked, focus order, and focus indicator are valid.'], ['Capture on/off, hover, focus, disabled, and both themes.']),
    relatedComponents: ['checkbox', 'theme', 'field'],
    controls: { checked: { type: 'boolean', label: 'On', defaultValue: false }, disabled: { type: 'boolean', label: 'Disabled', defaultValue: false }, label: { type: 'text', label: 'Label', defaultValue: 'Enable notifications' } },
  },
  slider: {
    slug: 'slider',
    summary: 'A controlled native range input for choosing a numeric value from a bounded continuum.',
    sourcePath: 'src/components/Slider.tsx',
    packageExports: ['Slider', 'SliderProps'],
    anatomy: [{ name: 'Header row', description: 'Persistent label and optional formatted output.', required: true }, { name: 'Label', description: 'Accessible range name.', required: true, semanticElement: 'label' }, { name: 'Value output', description: 'Optional formatted current value.', required: false, semanticElement: 'output' }, { name: 'Track', description: '6px range with filled progress.', required: true }, { name: 'Thumb', description: '22px draggable value handle.', required: true }],
    visualSpec: { measurements: [{ property: 'Interaction row minimum height', value: '44px' }, { property: 'Track height', value: '6px' }, { property: 'Thumb', value: '22 × 22px' }, { property: 'Thumb border', value: '2px' }, { property: 'Label/track gap', value: '8px' }, { property: 'Hover thumb scale', value: '1.15×' }], rules: ['Always expose units through formatValue when the raw number is ambiguous.', 'Use a step appropriate to the precision users can perceive.', 'Provide direct numeric entry instead when exact values matter.'] },
    designTokens: [{ token: '--color-action-primary', purpose: 'Progress fill and thumb.' }, { token: '--color-surface2', purpose: 'Unfilled track.' }, { token: '--color-control-border', purpose: 'Track boundary.' }, { token: '--color-bg', purpose: 'Thumb border separation.' }, { token: '--color-focus', purpose: 'Range focus outline.' }],
    stateDefinitions: [
      { name: 'default', trigger: 'Enabled range input.', visual: 'Action-color progress and thumb over surface track.', behavior: 'Pointer drag and native key commands change by step.' },
      { name: 'disabled', trigger: 'disabled is true.', visual: '50% opacity, no hover scale, not-allowed cursor.', behavior: 'Focus and input are suppressed.' },
      { name: 'focus-visible', trigger: 'Keyboard focus reaches the range.', visual: '2px focus outline with 3px offset.', behavior: 'Arrow and page keys adjust value.' },
    ],
    keyboard: [{ key: 'Arrow Left / Down', action: 'Decreases by one step.' }, { key: 'Arrow Right / Up', action: 'Increases by one step.' }, { key: 'Home / End', action: 'Moves to minimum / maximum.' }, { key: 'Page Up / Page Down', action: 'Changes by the browser-defined larger increment.' }],
    accessibilitySpec: accessibility('Native input[type=range] associated with a label and optional output.', 'Required label names the range.', ['Provide useful min, max, and step values.', 'aria-valuetext must match the visible formatted output.', 'Do not use color alone to communicate the value; thumb position and output remain available.']),
    implementation: { importStatement: "import { Slider } from '@ai-created/ui';", clientComponent: false, notes: ['onChange receives a number, not an event.', 'Progress is clamped to 0-100%, including max equal to min.', 'formatValue drives both visible output and aria-valuetext.'] },
    guidance: { dos: ['Use for values users understand spatially, such as volume or opacity.', 'Show the current value when precision is useful.'], donts: ['Do not use for unbounded values.', 'Do not hide value formatting when units are unclear.'] },
    testing: testing(['Computes and clamps progress; handles max equal to min.', 'Formats output and aria-valuetext consistently.'], ['Pointer and keyboard changes call onChange with numeric values within range.'], ['Label, output htmlFor, range values, disabled state, and focus ring are valid.'], ['Capture min/mid/max, focus, hover, disabled, hidden output, custom units, and themes.']),
    relatedComponents: ['field', 'dropdown'],
    controls: { value: { type: 'number', label: 'Value', defaultValue: 50, min: 0, max: 100, step: 1 }, showValue: { type: 'boolean', label: 'Show value', defaultValue: true }, disabled: { type: 'boolean', label: 'Disabled', defaultValue: false } },
  },
  dropdown: {
    slug: 'dropdown',
    summary: 'An accessible controlled listbox for choosing one option in compact space.',
    sourcePath: 'src/components/Dropdown.tsx',
    packageExports: ['Dropdown', 'DropdownProps', 'DropdownOption'],
    anatomy: [{ name: 'Listbox root', description: 'Headless UI state and semantic owner.', required: true }, { name: 'Label', description: 'Persistent visible listbox name.', required: true }, { name: 'Trigger', description: 'Current selection or placeholder and disclosure icon.', required: true, semanticElement: 'button' }, { name: 'Options panel', description: 'Anchored, scrollable list of values.', required: true }, { name: 'Option', description: 'Selectable row with optional check marker and disabled state.', required: true }],
    visualSpec: { measurements: [{ property: 'Label-to-trigger gap', value: '8px' }, { property: 'Trigger padding', value: '16px left / 40px right / 12px vertical' }, { property: 'Option padding', value: '40px left / 16px right / 12px vertical' }, { property: 'Radius', value: '6px' }, { property: 'Panel maximum height', value: '240px' }, { property: 'Panel offset', value: '4px' }, { property: 'Icons', value: '16 × 16px' }], rules: ['Keep option labels on one line when possible; rows truncate overflow.', 'The panel width follows the trigger.', 'Use the placeholder only before a meaningful value is selected.'] },
    designTokens: [{ token: '--color-surface2', purpose: 'Trigger and active option background.' }, { token: '--color-surface', purpose: 'Options panel.' }, { token: '--color-control-border / --color-control-border-strong', purpose: 'Trigger resting and hover boundaries.' }, { token: '--color-border', purpose: 'Options panel border.' }, { token: '--color-focus', purpose: 'Trigger focus outline.' }, { token: '--color-accent', purpose: 'Selected check marker.' }, { token: '--shadow-elevation-medium / --layer-dropdown', purpose: 'Options elevation and stacking.' }],
    stateDefinitions: [
      { name: 'closed', trigger: 'Listbox is idle.', visual: 'Label and trigger show the current value or placeholder.', behavior: 'Activation opens the options panel.' },
      { name: 'open', trigger: 'Trigger is activated.', visual: 'Anchored options panel appears below the trigger.', behavior: 'Focus and keyboard navigation move through options.', accessibility: 'Headless UI exposes expanded and listbox relationships.' },
      { name: 'selected', trigger: 'Option value matches value.', visual: 'Primary text, medium weight, and accent check.', behavior: 'Choosing another option calls onChange and closes.' },
      { name: 'disabled', trigger: 'Group or option is disabled.', visual: '50% opacity and not-allowed cursor.', behavior: 'Disabled trigger cannot open; disabled option cannot select.' },
    ],
    keyboard: [{ key: 'Enter / Space / Arrow Down', action: 'Opens the listbox and enters option navigation.' }, { key: 'Arrow Up / Arrow Down', action: 'Moves the active option.' }, { key: 'Enter / Space', action: 'Selects the active option.' }, { key: 'Escape', action: 'Closes without changing selection.' }, { key: 'Home / End', action: 'Moves to the first / last enabled option.' }, { key: 'Typeahead', action: 'Moves to an option matching typed characters.' }],
    accessibilitySpec: accessibility('Headless UI Listbox with labelled button, options, and managed focus.', 'Required visible label names the listbox.', ['Use stable unique option values.', 'Provide a selected value that exists in options or intentionally show the placeholder.', 'Disabled options must not be the only way to explain unavailable choices.', 'Do not replace the listbox with a native select when rich behavior is unnecessary without considering platform benefits.']),
    implementation: { importStatement: "import { Dropdown, type DropdownOption } from '@ai-created/ui';", clientComponent: true, notes: ['Generic string values preserve domain types.', 'The trigger button ref is forwarded.', 'Headless UI owns option roles, focus, and dismissal.', 'An Enter handler normalizes trigger opening behavior.'] },
    guidance: { dos: ['Use for a moderate set of short, known options.', 'Sort or group options in a predictable domain order.'], donts: ['Do not use for two or three choices that should stay visible.', 'Do not use for large datasets that require search or virtualization.'] },
    testing: testing(['Resolves selected label and placeholder and forwards trigger ref.', 'Calls onChange with the selected enabled value.'], ['Open, arrow, select, escape, outside dismissal, typeahead, and disabled flows work.'], ['Label, expanded state, active descendant/option semantics, and focus restoration are valid.'], ['Capture closed/open, placeholder, selected, active, disabled option/trigger, overflow, themes, and top alignment beside a Field with an equal-height label.']),
    relatedComponents: ['radio-group', 'field'],
    controls: { value: { type: 'select', label: 'Value', defaultValue: 'recent', options: ['recent', 'name', 'status'] }, disabled: { type: 'boolean', label: 'Disabled', defaultValue: false }, label: { type: 'text', label: 'Label', defaultValue: 'Sort by' } },
  },
  tabs: {
    slug: 'tabs',
    summary: 'A controlled, keyboard-navigable tablist for switching between peer panels in place.',
    sourcePath: 'src/components/Tabs.tsx',
    packageExports: ['Tabs', 'TabsProps', 'Tab', 'useTabPanelProps'],
    anatomy: [{ name: 'Tablist', description: 'Named container coordinating arrow-key navigation.', required: true, semanticElement: '[role=tablist]' }, { name: 'Tab', description: 'Roving-focus button with label and optional icon.', required: true, semanticElement: 'button[role=tab]' }, { name: 'Active indicator', description: '2px accent line along the active tab.', required: true }, { name: 'Panel', description: 'Consumer-rendered view associated through useTabPanelProps.', required: true, semanticElement: '[role=tabpanel]' }],
    visualSpec: { measurements: [{ property: 'Tab padding', value: '16px horizontal / 8px vertical' }, { property: 'Tab gap', value: '2px' }, { property: 'Icon/label gap', value: '8px' }, { property: 'Active indicator', value: '2px high' }, { property: 'Top radius', value: '6px' }], rules: ['Use one concise row when possible.', 'The active state combines background, text, and indicator, not color alone.', 'Render only peer views that share the same page context.'], responsiveBehavior: ['The consumer should provide horizontal scrolling or an alternate pattern if labels overflow.', 'Do not wrap one tablist over multiple lines.'] },
    designTokens: [{ token: '--color-highlight', purpose: 'Active tab background.' }, { token: '--color-accent', purpose: 'Active indicator.' }, { token: '--color-text / --color-text2 / --color-text3', purpose: 'Active, hover, and inactive hierarchy.' }, { token: '--motion-fast', purpose: 'Color transition.' }],
    stateDefinitions: [
      { name: 'active', trigger: 'Tab key equals active.', visual: 'Highlight background, primary text, and accent indicator.', behavior: 'tabIndex is 0; associated panel is visible.', accessibility: 'aria-selected true.' },
      { name: 'inactive', trigger: 'Tab key differs from active.', visual: 'Tertiary text that strengthens on hover.', behavior: 'tabIndex is -1; activation selects it.', accessibility: 'aria-selected false.' },
      { name: 'focus-visible', trigger: 'Roving focus reaches a tab.', visual: 'Global button focus outline.', behavior: 'Arrow, Home, and End select and focus another tab.' },
    ],
    keyboard: [{ key: 'Arrow Right / Arrow Left', action: 'Selects and focuses the next / previous tab with wraparound.' }, { key: 'Home / End', action: 'Selects and focuses the first / last tab.' }, { key: 'Enter / Space', action: 'Native button activation selects a focused tab.' }, { key: 'Tab', action: 'Moves from the active tab into the active panel or next focus target.' }],
    accessibilitySpec: accessibility('Explicit tablist, tab, and tabpanel roles with aria-selected, aria-controls, and aria-labelledby.', 'Required label names the tablist; each tab label names its tab.', ['Pass the same stable id to Tabs and useTabPanelProps so relationships are emitted.', 'Render one panel for every tab key and hide inactive panels.', 'Keep tab keys DOM-id safe and unique.', 'Icons are decorative.']),
    implementation: { importStatement: "import { Tabs, useTabPanelProps, type Tab } from '@ai-created/ui';", clientComponent: true, notes: ['Tabs is controlled and uses automatic activation during arrow navigation.', 'Without a shared provided id, DOM ids are generated but cross-component aria relationships are intentionally omitted.', 'useTabPanelProps returns role, ids, tabIndex, and hidden.'] },
    guidance: { dos: ['Use for two to six related peer views.', 'Keep labels short and use a stable default tab.'], donts: ['Do not use tabs for primary site navigation.', 'Do not place unrelated tasks in the same tablist.'] },
    testing: testing(['Emits ids and panel relationships only when the stable id is shared.', 'Handles empty tabs without errors.'], ['Click, arrow wraparound, Home, End, focus movement, and panel visibility work.'], ['Roving tabIndex, selected state, tablist name, and panel relationships are valid.'], ['Capture each active tab, focus, optional icons, overflow pressure, and themes.']),
    relatedComponents: ['button', 'surface'],
    controls: { active: { type: 'select', label: 'Active tab', defaultValue: 'overview', options: ['overview', 'activity', 'settings'] } },
  },
  dialog: {
    slug: 'dialog',
    summary: 'A ready-made animated modal dialog for a short focused task or decision.',
    sourcePath: 'src/components/Dialog.tsx',
    packageExports: ['Dialog', 'DialogProps', 'DialogSize'],
    anatomy: [{ name: 'Backdrop', description: 'Full-viewport overlay separating the dialog from page content.', required: true }, { name: 'Dialog panel', description: 'Centered bounded content surface.', required: true }, { name: 'Header', description: 'Optional title, description, and close button.', required: false }, { name: 'Close action', description: '44 × 44px labelled dismiss button.', required: false, semanticElement: 'button' }, { name: 'Body', description: 'Consumer task content.', required: true }],
    visualSpec: { measurements: [{ property: 'Viewport padding', value: '16px' }, { property: 'Panel max width', value: '384 / 512 / 672 / 896px', notes: 'sm / md / lg / xl.' }, { property: 'Radius', value: '6px' }, { property: 'Header padding', value: '24px horizontal / 16px vertical' }, { property: 'Body padding', value: '24px horizontal / 20px vertical' }, { property: 'Close target', value: '44 × 44px' }, { property: 'Close glyph inset', value: '24px', notes: 'The 16px glyph aligns with the header content edge inside its 44px target.' }], rules: ['Keep the title visible and specific.', 'Use one scroll strategy; Dialog itself does not constrain body height.', 'Keep primary and dismissal actions inside the panel.'], responsiveBehavior: ['Panel width is fluid up to its size max-width and viewport padding.', 'Consider Modal for long or structurally rich content.'] },
    designTokens: [{ token: '--color-overlay', purpose: 'Backdrop.' }, { token: '--color-surface', purpose: 'Panel.' }, { token: '--color-border', purpose: 'Panel and header divider.' }, { token: '--color-text / --color-text2 / --color-text3', purpose: 'Title, description, and close icon.' }, { token: '--color-focus', purpose: 'Close focus outline.' }],
    stateDefinitions: [
      { name: 'closed', trigger: 'open is false.', visual: 'Backdrop and panel are absent after transition.', behavior: 'Page remains interactive.' },
      { name: 'open', trigger: 'open is true.', visual: 'Backdrop and centered panel are visible.', behavior: 'Focus is trapped and background interaction is inert.' },
      { name: 'entering', trigger: 'Opening transition.', visual: 'Backdrop fades; panel fades and scales from 95% over 200ms.', behavior: 'Dialog becomes the active focus scope.' },
      { name: 'leaving', trigger: 'Closing transition.', visual: 'Backdrop and panel fade; panel scales to 95% over 150ms.', behavior: 'Focus returns after dismissal.' },
    ],
    keyboard: [{ key: 'Escape', action: 'Requests close through onClose.' }, { key: 'Tab / Shift+Tab', action: 'Cycles focus within the open dialog.' }, { key: 'Enter / Space', action: 'Activates the focused dialog control.' }],
    accessibilitySpec: accessibility('Headless UI dialog with optional DialogTitle and Description associations.', 'title supplies the accessible name when provided; otherwise body content must provide an accessible label.', ['Prefer always providing a title.', 'Provide at least one obvious dismissal method.', 'Do not put another modal dialog inside Dialog.', 'Restore focus to a meaningful trigger through the managed open state.']),
    implementation: { importStatement: "import { Dialog } from '@ai-created/ui';", clientComponent: true, notes: ['Headless UI manages focus trap, Escape, outside dismissal, inert background, and restoration.', 'Dialog stays in the tree while Transition controls visibility.', 'className applies to the panel.'] },
    guidance: { dos: ['Use for one short task with a clear completion path.', 'Write titles that describe the task, not generic “Dialog”.'], donts: ['Do not use for persistent workspace content.', 'Do not put large multi-step flows into the panel.'] },
    testing: testing(['Maps sizes and optional header content.', 'Calls onClose from close button and managed dismissal.'], ['Opening focus, focus trap, Escape, close button, backdrop, and restoration work.'], ['Dialog has a name/description and background is inert while open.'], ['Capture all sizes, header combinations, entering/open states, long content, and themes.']),
    relatedComponents: ['modal', 'confirm-dialog', 'button'],
    controls: { open: { type: 'boolean', label: 'Open', defaultValue: false }, size: { type: 'select', label: 'Size', defaultValue: 'md', options: ['sm', 'md', 'lg', 'xl'] }, title: { type: 'text', label: 'Title', defaultValue: 'Rename project' } },
  },
  modal: {
    slug: 'modal',
    summary: 'A composable Headless UI modal shell for richer application layouts with header, body, and footer regions.',
    sourcePath: 'src/components/Modal.tsx',
    packageExports: ['ModalOverlay', 'ModalPanel', 'ModalHeader', 'ModalBody', 'ModalFooter', 'ModalSize'],
    anatomy: [{ name: 'Overlay', description: 'Mounted dialog root, scroll container, backdrop, and focus scope.', required: true }, { name: 'Panel', description: 'Bounded flex-column Surface.', required: true }, { name: 'Header', description: 'Optional eyebrow, title, description, custom content, and close action.', required: true }, { name: 'Body', description: 'Primary content region with optional internal scrolling.', required: true }, { name: 'Footer', description: 'Optional bordered action region.', required: false }],
    visualSpec: { measurements: [{ property: 'Panel max width', value: '384 / 512 / 672 / 896px', notes: 'sm / md / lg / xl; shared with Dialog.' }, { property: 'Panel max height', value: 'viewport − 48px mobile / viewport − 64px md+' }, { property: 'Overlay padding', value: '16px mobile / 24px md+' }, { property: 'Top offset mobile', value: '64px' }, { property: 'Region padding', value: '20px horizontal mobile / 24px md; 16px vertical' }, { property: 'Header gap', value: '16px' }, { property: 'Close target', value: '44 × 44px' }, { property: 'Close glyph inset', value: '20px mobile / 24px md', notes: 'The 16px glyph aligns with the header content edge inside its 44px target.' }], rules: ['Compose regions only inside ModalPanel.', 'Keep a single scrollable body between fixed header and footer.', 'Use alertdialog role only for consequential confirmations.'], responsiveBehavior: ['Aligns near the top on small screens and centers from sm upward.', 'Body scrolls within a viewport-bounded panel.'] },
    designTokens: [{ token: '--color-overlay', purpose: 'Backdrop.' }, { token: '--color-surface / --color-border', purpose: 'Panel and dividers through Surface.' }, { token: '--color-text / --color-text2', purpose: 'Heading and description.' }, { token: '--radius-md', purpose: 'Panel radius.' }],
    stateDefinitions: [
      { name: 'closed', trigger: 'ModalOverlay is not rendered.', visual: 'No modal UI.', behavior: 'Page owns focus and scrolling.' },
      { name: 'open', trigger: 'ModalOverlay is mounted.', visual: 'Blurred overlay and panel are visible.', behavior: 'Headless UI traps focus, locks background interaction, and handles Escape.' },
      { name: 'nested', trigger: 'A modal is opened from another focus scope.', visual: 'Higher-level modal remains visually subordinate.', behavior: 'Use sparingly and verify focus restoration at each level.', accessibility: 'Every dialog must retain a unique name.' },
      { name: 'focus-visible', trigger: 'Keyboard focus reaches a control.', visual: 'The focused child component supplies its standard ring.', behavior: 'Tab remains within the active dialog.' },
    ],
    keyboard: [{ key: 'Escape', action: 'Requests onClose when supplied.' }, { key: 'Tab / Shift+Tab', action: 'Cycles through focusable modal content.' }, { key: 'Enter / Space', action: 'Activates the focused control.' }],
    accessibilitySpec: accessibility('Headless UI Dialog; Header uses DialogTitle and Description, and alertdialog is supported.', 'ModalHeader heading supplies the name; description supplies supporting text.', ['Always include ModalHeader with a meaningful heading or provide an equivalent Headless UI title.', 'Supply an onClose control unless the operation intentionally prevents dismissal.', 'Keep footer action order and labels explicit.']),
    implementation: { importStatement: "import { ModalOverlay, ModalPanel, ModalHeader, ModalBody, ModalFooter } from '@ai-created/ui';", clientComponent: true, notes: ['Render ModalOverlay conditionally; it is always open while mounted.', 'onClose is optional because ConfirmDialog can suppress dismissal while loading.', 'closeOnBackdrop affects pointer backdrop dismissal only.', 'ModalBody scroll defaults to true.'] },
    guidance: { dos: ['Use for rich but bounded application tasks.', 'Keep the primary action in the footer and close action in the header.'], donts: ['Do not mount without a panel and title.', 'Do not place essential page navigation inside a modal.'] },
    testing: testing(['Maps the shared Dialog panel sizes and every region option.', 'Optional onClose behavior is deterministic.'], ['Escape, backdrop setting, 44px close button, focus trap, body scrolling, and restoration work.'], ['Dialog naming, description, role, focus order, and inert background are valid.'], ['Capture sizes, mobile top alignment, desktop centering, overflow, header/footer variants, and themes.']),
    relatedComponents: ['dialog', 'confirm-dialog', 'surface', 'button'],
    controls: { open: { type: 'boolean', label: 'Open', defaultValue: false }, size: { type: 'select', label: 'Size', defaultValue: 'lg', options: ['sm', 'md', 'lg', 'xl'] }, closeOnBackdrop: { type: 'boolean', label: 'Backdrop closes', defaultValue: true }, scroll: { type: 'boolean', label: 'Scrollable body', defaultValue: true } },
  },
  'confirm-dialog': {
    slug: 'confirm-dialog',
    summary: 'A constrained alert dialog for confirming one consequential or irreversible action.',
    sourcePath: 'src/components/ConfirmDialog.tsx',
    packageExports: ['ConfirmDialog', 'ConfirmDialogProps'],
    anatomy: [{ name: 'Alert dialog', description: 'Small Modal composition with alertdialog semantics.', required: true }, { name: 'Title', description: 'Names the exact action under confirmation.', required: true }, { name: 'Description', description: 'Optional consequence and scope explanation.', required: false }, { name: 'Cancel action', description: 'Safe dismissal path.', required: true, semanticElement: 'button' }, { name: 'Confirm action', description: 'Executes the consequential operation.', required: true, semanticElement: 'button' }],
    visualSpec: { measurements: [{ property: 'Panel width', value: 'max 384px' }, { property: 'Footer action gap', value: '12px' }, { property: 'Header/body/footer padding', value: '20px horizontal mobile / 24px md' }, { property: 'Close glyph inset', value: '20px mobile / 24px md', notes: 'Inherited from ModalHeader while the dialog is dismissible.' }], rules: ['Name the specific object and action.', 'Place Cancel before Confirm in the footer.', 'Use destructive styling only for destructive consequences.'] },
    designTokens: [{ token: '--color-overlay', purpose: 'Modal backdrop.' }, { token: '--color-surface / --color-border', purpose: 'Panel and dividers.' }, { token: '--color-action-primary', purpose: 'Standard confirmation.' }, { token: '--color-action-destructive', purpose: 'Destructive confirmation.' }, { token: '--color-on-action', purpose: 'Filled action foreground.' }, { token: '--color-text / --color-text2', purpose: 'Title and description.' }],
    stateDefinitions: [
      { name: 'closed', trigger: 'open is false.', visual: 'Nothing is rendered.', behavior: 'No focus scope exists.' },
      { name: 'open', trigger: 'open is true.', visual: 'Small alert dialog with cancel and confirm actions.', behavior: 'Focus is trapped; dismissal calls onCancel.' },
      { name: 'loading', trigger: 'loading is true.', visual: 'Both actions are disabled and confirm label becomes loadingLabel.', behavior: 'Escape, backdrop, header close, cancel, and confirm activation are blocked.', accessibility: 'Disabled buttons expose unavailability; the label communicates work in progress.' },
    ],
    keyboard: [{ key: 'Escape', action: 'Cancels and closes.', condition: 'Only while not loading.' }, { key: 'Tab / Shift+Tab', action: 'Moves between available actions within the dialog.' }, { key: 'Enter / Space', action: 'Activates the focused cancel or confirm button.', condition: 'Only while not loading.' }],
    accessibilitySpec: accessibility('Headless UI alertdialog composed from Modal primitives.', 'Required title names the alert dialog; optional Description is associated by Headless UI.', ['Initial focus should land on the safest useful control for the context; verify Headless UI behavior in integration.', 'Explain irreversible consequences before the action.', 'Do not rely on destructive color; button text must be specific.', 'Expose completion or failure after loading ends.']),
    implementation: { importStatement: "import { ConfirmDialog } from '@ai-created/ui';", clientComponent: true, notes: ['Returns null while closed.', 'destructive changes the confirm visual variant; it does not alter semantics.', 'loading suppresses every dismissal callback and action.', 'The parent owns async state and closes on success.'] },
    guidance: { dos: ['Reserve confirmation for meaningful consequences.', 'Use labels such as Delete project instead of Confirm.'], donts: ['Do not interrupt routine reversible actions.', 'Do not allow the dialog to close while its operation is unresolved.'] },
    testing: testing(['Closed returns null; defaults and destructive variant map correctly.', 'Loading disables all dismissal paths and changes the label.'], ['Cancel, confirm, Escape, backdrop, focus trap, loading, and restoration work.'], ['Alertdialog is named/described and actions have specific names and correct disabled state.'], ['Capture regular/destructive, description absent/present, loading, long labels, and themes.']),
    relatedComponents: ['modal', 'dialog', 'button'],
    controls: { open: { type: 'boolean', label: 'Open', defaultValue: false }, destructive: { type: 'boolean', label: 'Destructive', defaultValue: true }, loading: { type: 'boolean', label: 'Loading', defaultValue: false }, title: { type: 'text', label: 'Title', defaultValue: 'Delete project?' } },
  },
  tooltip: {
    slug: 'tooltip',
    summary: 'A brief, non-interactive description shown from pointer, focus, or touch.',
    sourcePath: 'src/components/Tooltip.tsx',
    packageExports: ['Tooltip', 'TooltipProps', 'TooltipPosition'],
    anatomy: [{ name: 'Wrapper', description: 'Inline trigger measurement context.', required: true, semanticElement: 'span' }, { name: 'Trigger', description: 'Exactly one cloned focusable element.', required: true }, { name: 'Tooltip bubble', description: 'Portalled, viewport-positioned description associated while visible.', required: true, semanticElement: '[role=tooltip]' }],
    visualSpec: { measurements: [{ property: 'Bubble padding', value: '12px horizontal / 6px vertical' }, { property: 'Trigger offset', value: '8px' }, { property: 'Viewport inset', value: '8px minimum' }, { property: 'Maximum width', value: '240px' }, { property: 'Radius', value: '6px' }, { property: 'Entrance', value: '200ms fade' }], rules: ['Keep content brief, plain text, and non-interactive.', 'Preferred placement flips when its opposite side has available space and clamps to the viewport.', 'Do not hide essential instructions in the tooltip.'] },
    designTokens: [{ token: '--color-surface', purpose: 'Bubble background.' }, { token: '--color-border', purpose: 'Bubble border.' }, { token: '--color-text2', purpose: 'Tooltip text.' }, { token: '--radius-md', purpose: 'Bubble radius.' }, { token: '--shadow-elevation-medium / --layer-tooltip', purpose: 'Portalled elevation and stacking.' }, { token: '--motion-fast', purpose: 'Entrance fade.' }],
    stateDefinitions: [
      { name: 'hidden', trigger: 'No active pointer, focus, or toggled touch.', visual: 'Bubble is not mounted.', behavior: 'Trigger retains its original aria-describedby.' },
      { name: 'visible', trigger: 'Pointer hover remains for delay milliseconds.', visual: 'Bubble appears at the resolved viewport position.', behavior: 'Pointer may cross onto the bubble without dismissing it; leaving both hides after a short bridge delay.', accessibility: 'Tooltip id is appended to aria-describedby while visible.' },
      { name: 'focused', trigger: 'Trigger receives focus for delay milliseconds.', visual: 'Same bubble as hover.', behavior: 'Blur hides it.' },
      { name: 'touch-visible', trigger: 'Trigger receives touchstart.', visual: 'Bubble toggles immediately.', behavior: 'Another touch or outside touch hides it.' },
    ],
    keyboard: [{ key: 'Tab / Shift+Tab', action: 'Focuses the child trigger; tooltip appears after delay.' }, { key: 'Escape', action: 'Dismisses the tooltip without moving focus.' }],
    accessibilitySpec: accessibility('role=tooltip associated through aria-describedby only while visible.', 'content provides the supplemental description; the trigger still needs its own accessible name.', ['Wrap exactly one focusable trigger.', 'Preserve existing trigger event handlers and aria-describedby; the component composes them.', 'Keep content non-interactive and supplemental.', 'Do not use the tooltip as the accessible name of an icon button.']),
    implementation: { importStatement: "import { Tooltip } from '@ai-created/ui';", clientComponent: true, notes: ['The child element is cloned to compose hover, focus, blur, and touch handlers.', 'Show and hover-bridge timeouts are cleared on hide and unmount.', 'The bubble portals to document.body, flips to the opposite side when needed, clamps to the viewport, and tracks scroll/resize.', 'Escape and outside touch listeners exist only while visible.'] },
    guidance: { dos: ['Use to explain an unfamiliar icon or compact control.', 'Keep one short sentence or phrase.'], donts: ['Do not put links, buttons, or form fields inside.', 'Do not repeat a visible label verbatim without adding value.'] },
    testing: testing(['Composes existing child handlers and aria-describedby.', 'Clears timers and temporary listeners.'], ['Hover/focus delay, pointer travel onto the bubble, Escape, leave/blur, touch toggle, outside touch, flip, clamp, scroll, and resize behave correctly.'], ['Role, id relationship, trigger name, Escape dismissal, and keyboard discoverability are valid.'], ['Capture all positions, viewport edges, wrapping at max width, focus/hover visibility, and themes.']),
    relatedComponents: ['button'],
    controls: { position: { type: 'select', label: 'Position', defaultValue: 'top', options: ['top', 'bottom', 'left', 'right'] }, delay: { type: 'number', label: 'Delay', defaultValue: 300, min: 0, max: 1000, step: 50, unit: 'ms' }, content: { type: 'text', label: 'Content', defaultValue: 'Copy link' } },
  },
  'themed-hero-image': {
    slug: 'themed-hero-image',
    summary: 'A decorative, theme-aware hero background with coordinated overlays, fades, and optional light blending.',
    sourcePath: 'src/components/ThemedHeroImage.tsx',
    packageExports: ['ThemedHeroImage', 'ThemedHeroImageProps'],
    anatomy: [{ name: 'Positioning root', description: 'Absolute full-bleed media container.', required: true, semanticElement: 'div' }, { name: 'Dark image', description: 'Required default decorative image.', required: true }, { name: 'Light image', description: 'Optional cross-faded light-theme image.', required: false }, { name: 'Overlay', description: 'Theme-aware contrast layer.', required: false }, { name: 'Top/bottom fades', description: 'Optional gradients blending into page background.', required: false }],
    visualSpec: { measurements: [{ property: 'Bounds', value: 'absolute inset 0' }, { property: 'Image fit', value: 'cover' }, { property: 'Theme cross-fade', value: '500ms during theme transitions' }, { property: 'Fade depth', value: 'one third of container height' }, { property: 'Default quality', value: '85' }], rules: ['Parent must establish positioning and an explicit height.', 'Maintain sufficient text contrast over both images.', 'Use only for decorative imagery; content images require semantic Image usage.'], responsiveBehavior: ['sizes defaults to 100vw and should be narrowed when the image is not full viewport width.', 'objectPosition controls art-direction focus as the container crops.'] },
    designTokens: [{ token: '--hero-overlay-default / strong / soft', purpose: 'Theme-specific contrast overlays.' }, { token: '--hero-image-dark-opacity / --hero-image-light-opacity', purpose: 'Theme image swap.' }, { token: '--color-bg', purpose: 'Top and bottom fade destination.' }, { token: '--motion-slow', purpose: 'Theme cross-fade.' }],
    stateDefinitions: [
      { name: 'dark theme', trigger: 'Root does not have light class.', visual: 'Dark source is opaque; optional light source is transparent; dark overlay values apply.', behavior: 'Image remains decorative.' },
      { name: 'light theme', trigger: 'Root has light class.', visual: 'Optional light source is opaque and dark source transparent; warm overlay values apply.', behavior: 'blendLight can multiply the image into the light surface.' },
    ],
    keyboard: [],
    accessibilitySpec: accessibility('Next Image elements use empty alt and aria-hidden; overlays are plain decorative divs.', 'No accessible name by design.', ['Use only when the image conveys no information that is absent from nearby text.', 'Do not put interactive content inside the component.', 'Verify overlaid text contrast independently in both themes and crop sizes.']),
    implementation: { importStatement: "import { ThemedHeroImage } from '@ai-created/ui';", clientComponent: false, notes: ['Requires Next.js Image configuration for external sources.', 'priority applies only to the dark image; use it for an above-the-fold hero.', 'If lightSrc is absent, the dark image remains fully visible in both themes.', 'overlay none deliberately renders no overlay node.'] },
    guidance: { dos: ['Art-direct dark and light sources for comparable subject placement.', 'Set accurate sizes and use priority only above the fold.'], donts: ['Do not use for product screenshots or informative charts.', 'Do not assume an overlay guarantees accessible contrast.'] },
    testing: testing(['Maps overlay, fades, blend, sizes, quality, priority, and object position.', 'Renders one or two images as configured.'], ['Theme class changes swap opacity without affecting layout.'], ['Images remain hidden from the accessibility tree and overlaid copy passes contrast.'], ['Capture dark/light, every overlay, fades, blend, and representative crop ratios.']),
    relatedComponents: ['theme', 'surface'],
    controls: { overlay: { type: 'select', label: 'Overlay', defaultValue: 'default', options: ['default', 'strong', 'soft', 'none'] }, fadeTop: { type: 'boolean', label: 'Top fade', defaultValue: false }, fadeBottom: { type: 'boolean', label: 'Bottom fade', defaultValue: false }, blendLight: { type: 'boolean', label: 'Light blend', defaultValue: false } },
  },
  theme: {
    slug: 'theme',
    summary: 'Application-level dark/light and accent state, persistence, reduced-motion configuration, and a ready-made switch action.',
    sourcePath: 'src/components/ThemeProvider.tsx',
    packageExports: ['ThemeProvider', 'useTheme', 'ThemeToggle', 'Theme', 'Accent', 'accentNames', 'ThemeContextValue', 'ThemeProviderProps'],
    anatomy: [{ name: 'Theme provider', description: 'Context owner and document class/data-attribute synchronizer.', required: true }, { name: 'Motion configuration', description: 'Global reduced-motion policy set to user preference.', required: true }, { name: 'Theme toggle', description: 'Optional 44px icon action that reads and changes context.', required: false, semanticElement: 'button' }, { name: 'Root theme class', description: 'Document hook that activates dark/light semantic token overrides and native color-scheme.', required: true, semanticElement: 'html.light' }, { name: 'Root accent attribute', description: 'Document hook selecting the active accent scheme.', required: true, semanticElement: 'html[data-accent]' }],
    visualSpec: { measurements: [{ property: 'ThemeToggle target', value: '44 × 44px' }, { property: 'ThemeToggle icon', value: '18 × 18px' }, { property: 'Appearance transition', value: '300ms colors / 500ms hero images' }, { property: 'Toggle tap scale', value: '0.85×' }, { property: 'Toggle hover scale', value: '1.1×' }], rules: ['Wrap the application once.', 'Use semantic tokens so components switch without per-component theme or accent branches.', 'Initialize the html class and data-accent before paint in the consuming app to avoid an appearance flash.'] },
    designTokens: [{ token: '--color-bg / surface / surface2', purpose: 'Theme foundations.' }, { token: '--color-text / text2 / text3', purpose: 'Theme typography hierarchy.' }, { token: '--color-accent* / --color-action-primary* / --color-focus / --color-selection', purpose: 'Role-tuned active accent scheme colors.' }, { token: '--color-success / warning / info / error*', purpose: 'Stable feedback semantics that never follow the accent.' }, { token: '--motion-base / --motion-slow', purpose: 'Theme and image transitions.' }],
    stateDefinitions: [
      { name: 'dark', trigger: 'Default or saved dark preference.', visual: 'Neutral-950 background, light text, dark semantic palette; toggle shows sun.', behavior: 'toggleTheme stores light and adds html.light.' },
      { name: 'light', trigger: 'Saved or pre-rendered light preference.', visual: 'Warm-neutral background, dark text, light semantic palette; toggle shows moon.', behavior: 'toggleTheme stores dark and removes html.light.' },
      { name: 'accent scheme', trigger: 'Controlled accent prop, or uncontrolled saved accent > existing data-accent > defaultAccent > red.', visual: 'Accent, primary action, focus, selection, and supporting accent roles adopt the selected family.', behavior: 'Uncontrolled setAccent persists, updates html[data-accent], and reports through onAccentChange. Controlled accent is fixed; setAccent reports through onAccentChange without persistence, or is a no-op when no callback exists. Destructive and feedback roles remain unchanged.' },
    ],
    keyboard: [{ key: 'Enter / Space', action: 'Activates ThemeToggle.' }, { key: 'Tab / Shift+Tab', action: 'Moves focus to or from ThemeToggle.' }],
    accessibilitySpec: accessibility('Context provider plus native motion button; ThemeToggle has a state-dependent aria-label and title.', 'ThemeToggle announces the action it will perform, such as Switch to light mode.', ['Run a pre-hydration appearance script or equivalent to keep theme, accent, and context state aligned at first paint.', 'Do not encode information solely in the active theme or accent.', 'Every accent role must retain its browser-tested contrast contract across all dark/light foundations.', 'MotionConfig and CSS reduced-motion rules must remain enabled.']),
    implementation: { importStatement: "import { ThemeProvider, ThemeToggle, useTheme } from '@ai-created/ui';", clientComponent: true, notes: ['ThemeProvider reads localStorage after mount and falls back to the existing html class or dark.', 'accent is controlled and fixed; defaultAccent is the uncontrolled fallback and red is the default.', 'onAccentChange receives setAccent requests in either mode; controlled changes are never persisted.', 'Uncontrolled precedence is valid localStorage[accent] > existing html[data-accent] > defaultAccent > red.', 'toggleTheme updates context, localStorage, html.light, and temporarily adds theme-transitioning.', 'Uncontrolled setAccent updates context, localStorage[accent], html[data-accent], and calls onAccentChange when provided.', 'The transition class is removed after the 500ms theme-media window, restarted on repeated toggles, and cleaned on unmount.', 'The token stylesheet sets color-scheme for native controls in both modes.', 'useTheme outside a provider receives the safe dark/red default context.'] },
    guidance: { dos: ['Apply the initial document class before React hydration.', 'Use useTheme only for behavior or media that cannot be expressed through tokens.'], donts: ['Do not hard-code dark-only colors inside components.', 'Do not nest competing ThemeProviders.'] },
    testing: testing(['Resolves saved, existing-class, default themes, and uncontrolled accent precedence.', 'Controlled accent wins over storage/document/default; callback and no-op behavior are covered.', 'toggleTheme updates context, storage, and document class.', 'Uncontrolled setAccent updates context, storage, and html[data-accent].'], ['ThemeToggle changes mode by pointer and keyboard and updates its label/icon.'], ['Accent choices have an accessible name and do not communicate meaning by color alone; reduced-motion preference is honored.'], ['Capture every foundation and public component across all nine accents and both themes, including transition and no-motion states; browser-test accent text, muted text, borders, actions, focus, selection, and action foregrounds on bg, surface, and surface2.']),
    relatedComponents: ['themed-hero-image', 'motion-helpers', 'button'],
    controls: { theme: { type: 'select', label: 'Theme', defaultValue: 'dark', options: ['dark', 'light'] }, accent: { type: 'select', label: 'Accent', defaultValue: 'red', options: ['red', 'green', 'blue', 'orange', 'yellow', 'purple', 'teal', 'pink', 'magenta'] } },
  },
  cn: {
    slug: 'cn',
    summary: 'The class-composition utility that filters conditional fragments and resolves conflicting Tailwind utilities.',
    sourcePath: 'src/lib/utils.ts',
    packageExports: ['cn'],
    anatomy: [{ name: 'Input fragments', description: 'Ordered strings or falsy conditional values.', required: true }, { name: 'Falsy filter', description: 'Removes false, null, and undefined inputs.', required: true }, { name: 'Tailwind merge', description: 'Resolves utility conflicts by precedence.', required: true }, { name: 'Class string', description: 'Serializable final className.', required: true }],
    visualSpec: { measurements: [{ property: 'Output', value: 'One whitespace-delimited class string' }], rules: ['Put default classes first and the consumer className last when overrides are allowed.', 'Do not use arbitrary class conflicts as a substitute for explicit variants.', 'Focus and semantic-state utilities are part of the component contract.'] },
    designTokens: [{ token: 'Consumer-defined semantic tokens', purpose: 'cn preserves token-backed Tailwind utilities while resolving conflicts.' }],
    stateDefinitions: [{ name: 'not applicable', trigger: 'Called during class composition.', visual: 'No visual output by itself.', behavior: 'Returns the Tailwind-merged string.' }],
    keyboard: [],
    accessibilitySpec: accessibility('No DOM semantics; output affects the consuming element only.', 'Not applicable.', ['Do not merge away required focus-visible, disabled, hidden, or contrast styles.', 'The consuming component remains responsible for semantics.']),
    implementation: { importStatement: "import { cn } from '@ai-created/ui';", clientComponent: false, notes: ['Accepts only string, false, null, and undefined fragments.', 'Falsy values are filtered before tailwind-merge runs.', 'Later conflicting utilities take precedence according to tailwind-merge.'] },
    guidance: { dos: ['Use for conditional variants and intentional consumer overrides.', 'Keep class ordering predictable.'], donts: ['Do not pass untrusted class strings.', 'Do not hide component variant logic in long ad-hoc condition chains.'] },
    testing: testing(['Filters falsy values and preserves non-conflicting order.', 'Resolves representative Tailwind conflicts in favor of later utilities.'], ['Not applicable.'], ['Verify merged output retains focus and disabled utilities.'], ['Not applicable; visual coverage belongs to consumers.']),
    relatedComponents: ['button', 'surface'],
    controls: { base: { type: 'text', label: 'Base classes', defaultValue: 'rounded-md px-4 py-3' }, conditional: { type: 'text', label: 'Conditional classes', defaultValue: 'bg-surface2 text-text' }, enabled: { type: 'boolean', label: 'Include conditional', defaultValue: true } },
  },
  'motion-helpers': {
    slug: 'motion-helpers',
    summary: 'Shared timing, easing, offsets, reveal recipes, and subtle hover behavior for Framer Motion.',
    sourcePath: 'src/lib/motion.ts',
    packageExports: ['motionDuration', 'motionOffset', 'motionEase', 'staggerDelay', 'fadeUpMotion', 'inViewFadeUpMotion', 'subtleHoverMotion', 'borderHoverMotion'],
    anatomy: [{ name: 'Duration scale', description: 'Six named timings from instant to ambient.', required: true }, { name: 'Offset scale', description: 'Reveal and hover travel distances.', required: true }, { name: 'Easing scale', description: 'Standard cubic bezier and named Framer easings.', required: true }, { name: 'Reveal helpers', description: 'Serializable Framer Motion prop objects for mount and in-view entrance.', required: true }, { name: 'Hover helpers', description: 'Serializable lift and border-emphasis prop objects.', required: true }],
    visualSpec: { measurements: [{ property: 'Durations', value: '150 / 200 / 300 / 500 / 600 / 1500ms' }, { property: 'Reveal offsets', value: '16 / 20 / 30px' }, { property: 'Hover offsets', value: '2 / 4px' }, { property: 'Default stagger', value: '100ms per item' }], rules: ['Use motion to clarify hierarchy or state, not to decorate every element.', 'Prefer shared values over one-off durations and distances.', 'In-view reveals run once by default.', 'Do not rely on motion alone to communicate meaning.'] },
    designTokens: [{ token: '--motion-fast', purpose: 'CSS equivalent of 200ms interactions.' }, { token: '--motion-base', purpose: 'CSS equivalent of 300ms transitions.' }, { token: '--motion-slow', purpose: 'CSS equivalent of 500ms reveals/cross-fades.' }, { token: '--color-border-strong', purpose: 'Default borderHoverMotion emphasis.' }],
    stateDefinitions: [
      { name: 'entry', trigger: 'fadeUpMotion props mount.', visual: 'Opacity moves 0→1 while y moves to 0.', behavior: 'Runs immediately with optional delay.' },
      { name: 'in view', trigger: 'inViewFadeUpMotion enters viewport.', visual: 'Same fade-up treatment.', behavior: 'Runs once when observed.' },
      { name: 'hover', trigger: 'Pointer hover on a motion element.', visual: 'Element lifts 2px or 4px; border helper also strengthens border.', behavior: 'Returns over the shared fast duration.' },
      { name: 'reduced motion', trigger: 'User requests reduced motion under ThemeProvider MotionConfig.', visual: 'Framer Motion reduces transform motion according to user preference; global CSS collapses animation durations.', behavior: 'Meaning and interaction remain available without animation.' },
    ],
    keyboard: [],
    accessibilitySpec: accessibility('Helpers return presentation props only and do not alter DOM semantics.', 'Not applicable.', ['Render motion elements with the correct semantic element and focus behavior.', 'Use within ThemeProvider so MotionConfig honors the user preference.', 'Never delay essential content or input availability behind animation.', 'Avoid hover-only information.']),
    implementation: { importStatement: "import { fadeUpMotion, inViewFadeUpMotion, staggerDelay } from '@ai-created/ui';", clientComponent: false, notes: ['Helpers return plain serializable-compatible Framer Motion prop objects.', 'staggerDelay is deterministic and supports custom step/base.', 'borderHoverMotion accepts a CSS color string and defaults to the strong-border token.', 'Consumers provide the motion.* element and semantic tag.'] },
    guidance: { dos: ['Use subtle consistent motion for hierarchy changes.', 'Test the result with reduced motion enabled.'], donts: ['Do not stagger large lists so late content feels blocked.', 'Do not apply hover lift to controls where movement harms targeting.'] },
    testing: testing(['Constants stay immutable and helpers return exact expected prop shapes.', 'staggerDelay handles zero, custom base, and custom step.'], ['In-view fires once and hover returns to rest.', 'Reduced-motion configuration suppresses nonessential movement.'], ['No content or state is conveyed only through movement.'], ['Record representative entry, stagger, hover, and reduced-motion states.']),
    relatedComponents: ['theme', 'themed-hero-image', 'surface'],
    controls: { delay: { type: 'number', label: 'Delay', defaultValue: 0, min: 0, max: 2, step: 0.1, unit: 's' }, offset: { type: 'number', label: 'Offset', defaultValue: 20, min: 0, max: 60, step: 1, unit: 'px' }, duration: { type: 'number', label: 'Duration', defaultValue: 0.5, min: 0, max: 2, step: 0.05, unit: 's' } },
  },
} satisfies Record<ComponentSpecId, ComponentSpecDetails>;
