export {
  componentSpecs,
  componentSpecById,
  componentSpecCategories,
  componentSpecGroups,
  getComponentSpec,
  getComponentSpecsByCategory,
  isComponentSpecId,
  legacyComponentDocs,
} from './registry';

export {
  componentConstructionSpecs,
  nonVisualCanvasMechanicsStatement,
} from './construction';

export type {
  AccessibilitySpecification,
  AnatomyPart,
  AuthoringLimitations,
  AutoLayoutContract,
  AutoLayoutDirection,
  ComponentControl,
  ComponentConstructionSpecification,
  ComponentGovernance,
  ComponentSpec,
  ComponentSpecDetails,
  ComponentSpecId,
  ContentLimit,
  DesignAssetKind,
  DesignExposedProperty,
  DesignPropertyType,
  DesignTokenUsage,
  GovernanceStatus,
  ImplementationRecipe,
  ImplementationSpecification,
  KeyboardInteraction,
  LocalizationContract,
  NestedAssetContract,
  OverflowMode,
  ResponsiveContract,
  ResizingContract,
  ResizingMode,
  StateDefinition,
  TestingContract,
  UsageGuidance,
  VisualMeasurement,
  VisualSpecification,
} from './types';
