/** Hand-authored API reference used by the design-system playground. */
export interface ComponentApiRow {
  prop: string;
  type: string;
  defaultValue: string;
  description: string;
}

export interface ComponentDocEntry {
  id: string;
  name: string;
  category: 'Actions & feedback' | 'Fields & selection' | 'Overlays' | 'Layout & content' | 'Theme & media' | 'Utilities & motion';
  purpose: string;
  useWhen: string[];
  avoidWhen: string[];
  api: ComponentApiRow[];
  states: string[];
  accessibility: string[];
  composition: string[];
  code: string;
}

const row = (prop: string, type: string, defaultValue: string, description: string): ComponentApiRow => ({ prop, type, defaultValue, description });
const doc = (entry: Omit<ComponentDocEntry, 'api'> & { api: ComponentApiRow[] }): ComponentDocEntry => entry;

export const componentDocs: ComponentDocEntry[] = [
  doc({ id: 'button', name: 'Button / buttonStyles', category: 'Actions & feedback', purpose: 'Triggers an action with a consistent visual hierarchy.', useWhen: ['Submitting or confirming an action', 'Providing a compact inline or icon action'], avoidWhen: ['Navigation that should be a link', 'Non-interactive status text'], api: [row('variant', 'ButtonVariant', 'primary', 'primary, secondary, destructive, ghost, filter, filter-active, or icon.'), row('size', 'ButtonSize', 'md', 'inline, sm, md, lg, xl, or icon.'), row('fullWidth', 'boolean', 'false', 'Expands the button to the available width.'), row('type', 'button | submit | reset', 'button', 'Native button type.'), row('className', 'string', 'undefined', 'Additional classes.')], states: ['default', 'hover', 'focus-visible', 'disabled'], accessibility: ['Uses a native button and forwards its ref.', 'Provide an accessible name for icon-only buttons.'], composition: ['Children provide the button label or icon.', 'buttonStyles accepts the same visual options for custom elements.'], code: '<Button variant="primary">Save changes</Button>' }),
  doc({ id: 'badge', name: 'Badge', category: 'Actions & feedback', purpose: 'Displays a short status or classification label.', useWhen: ['Showing compact metadata or status'], avoidWhen: ['Long messages', 'Interactive controls'], api: [row('variant', 'BadgeVariant', 'default', 'default, muted, success, warning, error, or info.'), row('className', 'string', 'undefined', 'Additional classes.'), row('...props', 'HTMLAttributes<HTMLSpanElement>', 'undefined', 'Native span attributes.')], states: ['default', 'muted', 'success', 'warning', 'error', 'info'], accessibility: ['Renders a span; include meaningful text.'], composition: ['Place beside a title, table value, or list item.'], code: '<Badge variant="success">Ready</Badge>' }),
  doc({ id: 'surface', name: 'Surface / surfaceStyles', category: 'Layout & content', purpose: 'Provides a bordered, themed container for grouped content.', useWhen: ['Grouping related content', 'Creating cards or inset sections'], avoidWhen: ['A plain layout wrapper is sufficient'], api: [row('variant', 'SurfaceVariant', 'default', 'default, muted, accent, inset, success, warning, info, or error.'), row('padding', 'SurfacePadding', 'none', 'none, sm, md, lg, xl, or responsive.'), row('interaction', 'SurfaceInteraction', 'none', 'none, group, or within interaction styling.'), row('className', 'string', 'undefined', 'Additional classes.')], states: ['default', 'interactive group', 'interactive within'], accessibility: ['A div has no implicit landmark; add a heading or landmark when needed.'], composition: ['Use as the visual root of EmptyState and Notice.', 'surfaceStyles supports custom semantic elements.'], code: '<Surface variant="muted" padding="md">Content</Surface>' }),
  doc({ id: 'notice', name: 'Notice', category: 'Actions & feedback', purpose: 'Communicates an informational, success, warning, or error message.', useWhen: ['Explaining status near the relevant content'], avoidWhen: ['Transient toast notifications', 'Multi-step forms needing field-level errors'], api: [row('variant', 'NoticeVariant', 'default', 'default, info, success, warning, or error.'), row('title', 'string', 'undefined', 'Optional notice heading.'), row('children', 'ReactNode', 'undefined', 'Message content.'), row('role', 'string', 'status or alert', 'Override the semantic role.'), row('aria-live', 'polite | assertive | off', 'polite or assertive', 'Override announcement behavior.')], states: ['default', 'info', 'success', 'warning', 'error'], accessibility: ['Defaults to status, or alert for error.', 'Icons are decorative.'], composition: ['Use ErrorReport for expandable technical details.'], code: '<Notice variant="warning" title="Review required">Check the highlighted fields.</Notice>' }),
  doc({ id: 'skeleton', name: 'Skeleton', category: 'Actions & feedback', purpose: 'Reserves space while content is loading.', useWhen: ['Loading predictable content regions'], avoidWhen: ['Unknown layouts where a spinner is clearer'], api: [row('className', 'string', 'undefined', 'Controls size and shape with utility classes.'), row('...props', 'HTMLAttributes<HTMLDivElement>', 'undefined', 'Native div attributes.')], states: ['loading'], accessibility: ['The placeholder is hidden from assistive technology.', 'Keep the loading context in surrounding content.', 'Do not use as a replacement for a live loading announcement.'], composition: ['Match the dimensions of the content it replaces.'], code: '<Skeleton className="h-5 w-32" />' }),
  doc({ id: 'empty-state', name: 'EmptyState', category: 'Layout & content', purpose: 'Explains why a collection has no content and offers a next step.', useWhen: ['Empty lists, searches, or first-use screens'], avoidWhen: ['Loading states', 'Error states'], api: [row('icon', 'LucideIcon', 'undefined', 'Optional decorative icon.'), row('title', 'string', 'required', 'Short empty-state heading.'), row('description', 'string', 'undefined', 'Supporting explanation.'), row('children', 'ReactNode', 'undefined', 'Optional action content.'), row('className', 'string', 'undefined', 'Additional classes.')], states: ['empty'], accessibility: ['Icon is decorative.', 'Use a clear title and action label.'], composition: ['Place actions as children, commonly a Button.'], code: '<EmptyState title="No projects yet" description="Create one to get started."><Button>Create project</Button></EmptyState>' }),
  doc({ id: 'error-report', name: 'ErrorReport', category: 'Actions & feedback', purpose: 'Presents a user-facing error with optional copyable diagnostics.', useWhen: ['A recoverable operation failed', 'Users may need to share debug details'], avoidWhen: ['Sensitive diagnostics should never be exposed'], api: [row('message', 'string', 'required', 'User-facing error message.'), row('title', 'string', 'Something went wrong', 'Error heading.'), row('details', 'string | null', 'undefined', 'Optional technical details.'), row('timestamp', 'string', 'current ISO time', 'Optional diagnostic timestamp.')], states: ['collapsed', 'expanded', 'copied'], accessibility: ['Error notice is announced as an alert.', 'Details disclosure exposes expanded state and controls.'], composition: ['Place in the failed content region.'], code: '<ErrorReport message="Unable to load projects." details={error.message} />' }),
  doc({ id: 'field', name: 'Field family / style helpers', category: 'Fields & selection', purpose: 'Builds consistently labelled and described form controls.', useWhen: ['Text inputs, textareas, and grouped controls'], avoidWhen: ['Unrelated display text'], api: [row('FieldGroup', 'HTMLAttributes<HTMLDivElement>', 'undefined', 'Groups a label, control, and hint.'), row('FieldLabel', 'LabelHTMLAttributes<HTMLLabelElement>', 'undefined', 'Native label.'), row('FieldLegend', 'HTMLAttributes<HTMLSpanElement>', 'undefined', 'Visual legend text, not a semantic fieldset legend.'), row('FieldHint', 'HTMLAttributes<HTMLParagraphElement>', 'undefined', 'Supporting or validation text.'), row('TextInput', 'InputHTMLAttributes<HTMLInputElement>', 'undefined', 'Native text input.'), row('TextArea', 'TextareaHTMLAttributes<HTMLTextAreaElement>', 'undefined', 'Native textarea.')], states: ['default', 'focus-visible', 'disabled', 'invalid'], accessibility: ['Connect labels with htmlFor and id.', 'Use aria-describedby for hints and errors.'], composition: ['Use FieldGroup with FieldLabel, TextInput or TextArea, and FieldHint.', 'Style helpers return class names for custom controls.'], code: '<FieldGroup>\n  <FieldLabel htmlFor="email">Email</FieldLabel>\n  <TextInput id="email" type="email" aria-describedby="email-hint" />\n  <FieldHint id="email-hint">We will never share it.</FieldHint>\n</FieldGroup>' }),
  doc({ id: 'checkbox', name: 'Checkbox', category: 'Fields & selection', purpose: 'Controls an independent boolean choice.', useWhen: ['One or more independent options'], avoidWhen: ['Mutually exclusive choices'], api: [row('checked', 'boolean', 'required', 'Controlled checked state.'), row('onChange', '(checked: boolean) => void', 'required', 'Called when the value changes.'), row('label', 'string', 'required', 'Visible accessible label.'), row('disabled', 'boolean', 'false', 'Disables the native input.'), row('className', 'string', 'undefined', 'Additional classes.')], states: ['checked', 'unchecked', 'disabled', 'focus-visible'], accessibility: ['Uses a native checkbox and label.', 'Forwards the input ref.'], composition: ['Use inside a FieldGroup when additional help is needed.'], code: '<Checkbox checked={accepted} onChange={setAccepted} label="I agree" />' }),
  doc({ id: 'radio-group', name: 'RadioGroup', category: 'Fields & selection', purpose: 'Selects exactly one option from a set.', useWhen: ['Mutually exclusive choices'], avoidWhen: ['Independent toggles', 'Large searchable option sets'], api: [row('options', 'RadioOption<T>[]', 'required', 'Options with value, label, and optional disabled.'), row('value', 'T', 'required', 'Controlled selected value.'), row('onChange', '(value: T) => void', 'required', 'Called when selection changes.'), row('legend', 'string', 'required', 'Fieldset legend.'), row('name', 'string', 'generated id', 'Native radio group name.'), row('disabled', 'boolean', 'false', 'Disables the group.'), row('orientation', 'horizontal | vertical', 'vertical', 'Option layout.')], states: ['selected', 'unselected', 'disabled', 'focus-visible'], accessibility: ['Uses fieldset, legend, and native radio inputs.', 'Arrow keys follow native radio behavior.'], composition: ['Use RadioOption values as stable domain keys.'], code: '<RadioGroup options={options} value={size} onChange={setSize} legend="Size" />' }),
  doc({ id: 'toggle', name: 'Toggle', category: 'Fields & selection', purpose: 'Switches a setting between on and off.', useWhen: ['Immediate boolean settings'], avoidWhen: ['Actions that need confirmation', 'Multiple-choice selection'], api: [row('checked', 'boolean', 'required', 'Controlled switch state.'), row('onChange', '(checked: boolean) => void', 'required', 'Called when toggled.'), row('label', 'string', 'required', 'Visible label.'), row('disabled', 'boolean', 'false', 'Disables the switch.'), row('className', 'string', 'undefined', 'Additional classes.')], states: ['on', 'off', 'disabled', 'focus-visible'], accessibility: ['Uses role switch and aria-checked.', 'Forwards a button ref.'], composition: ['Use beside settings that apply immediately.'], code: '<Toggle checked={enabled} onChange={setEnabled} label="Enable notifications" />' }),
  doc({ id: 'slider', name: 'Slider', category: 'Fields & selection', purpose: 'Selects a numeric value within a range.', useWhen: ['Continuous or stepped numeric settings'], avoidWhen: ['Text values needing precise direct entry'], api: [row('value', 'number', 'required', 'Controlled numeric value.'), row('onChange', '(value: number) => void', 'required', 'Called with the new value.'), row('label', 'string', 'required', 'Accessible label.'), row('min', 'number', '0', 'Minimum value.'), row('max', 'number', '100', 'Maximum value.'), row('step', 'number', '1', 'Increment.'), row('showValue', 'boolean', 'true', 'Shows formatted value.'), row('formatValue', '(value: number) => string', 'String(value)', 'Formats the displayed value.')], states: ['default', 'disabled', 'focus-visible'], accessibility: ['Uses a labelled native range input.', 'Forwards the input ref.'], composition: ['Use formatValue for units or percentages.'], code: '<Slider label="Opacity" value={opacity} onChange={setOpacity} formatValue={(v) => `${v}%`} />' }),
  doc({ id: 'dropdown', name: 'Dropdown', category: 'Fields & selection', purpose: 'Selects one value from a compact list.', useWhen: ['A listbox fits the available space'], avoidWhen: ['A few always-visible options', 'Searchable large datasets'], api: [row('options', 'DropdownOption<T>[]', 'required', 'Options with value, label, and optional disabled.'), row('value', 'T', 'required', 'Controlled selected value.'), row('onChange', '(value: T) => void', 'required', 'Called on selection.'), row('label', 'string', 'required', 'Listbox label.'), row('placeholder', 'string', 'Select an option', 'Fallback text.'), row('disabled', 'boolean', 'false', 'Disables the listbox.')], states: ['closed', 'open', 'selected', 'disabled'], accessibility: ['Headless UI supplies listbox keyboard and focus behavior.', 'Forwards the trigger ref.'], composition: ['Use DropdownOption disabled for unavailable values.'], code: '<Dropdown options={options} value={sort} onChange={setSort} label="Sort by" />' }),
  doc({ id: 'tabs', name: 'Tabs / useTabPanelProps', category: 'Fields & selection', purpose: 'Switches between related views without leaving the page.', useWhen: ['Small sets of peer content panels'], avoidWhen: ['Navigation between pages'], api: [row('tabs', 'Tab<T>[]', 'required', 'Keys, labels, and optional icons.'), row('active', 'T', 'required', 'Active tab key.'), row('onChange', '(key: T) => void', 'required', 'Called when tab changes.'), row('label', 'string', 'required', 'Tablist accessible label.'), row('id', 'string', 'generated id', 'Stable group id for panels.')], states: ['active', 'inactive', 'focus-visible'], accessibility: ['Uses tablist, tab, and tabpanel relationships.', 'Arrow, Home, and End keys move focus.'], composition: ['Pass the same id to useTabPanelProps for each panel.'], code: 'const panel = useTabPanelProps("overview", active, tabsId);\n<Tabs id={tabsId} tabs={tabs} active={active} onChange={setActive} label="Project views" />\n<div {...panel}>Overview content</div>' }),
  doc({ id: 'dialog', name: 'Dialog', category: 'Overlays', purpose: 'Presents focused content above the current page.', useWhen: ['Short focused tasks or decisions'], avoidWhen: ['Persistent page content'], api: [row('open', 'boolean', 'required', 'Whether the dialog is shown.'), row('onClose', '() => void', 'required', 'Called on dismissal.'), row('title', 'string', 'undefined', 'Optional accessible title.'), row('description', 'string', 'undefined', 'Optional description.'), row('size', 'DialogSize', 'md', 'sm, md, lg, or xl.'), row('children', 'ReactNode', 'required', 'Dialog content.')], states: ['closed', 'open', 'entering', 'leaving'], accessibility: ['Headless UI manages focus, Escape, and restoration.', 'Title and description are associated when provided.'], composition: ['Keep the primary action and close affordance inside the dialog.'], code: '<Dialog open={open} onClose={() => setOpen(false)} title="Rename project">...</Dialog>' }),
  doc({ id: 'modal', name: 'Modal family', category: 'Overlays', purpose: 'Composes a themed modal from overlay, panel, header, body, and footer.', useWhen: ['Reusable application modal layouts'], avoidWhen: ['Simple inline disclosure'], api: [row('ModalOverlay.onClose', '() => void', 'undefined', 'Dismiss callback.'), row('ModalOverlay.closeOnBackdrop', 'boolean', 'true', 'Whether backdrop clicks dismiss.'), row('ModalPanel.size', 'ModalSize', 'lg', 'sm, md, lg, or xl.'), row('ModalHeader.heading', 'ReactNode', 'required', 'Heading content.'), row('ModalHeader.onClose', '() => void', 'undefined', 'Optional close action.'), row('ModalBody.scroll', 'boolean', 'true', 'Allows the body region to scroll.'), row('children', 'ReactNode', 'required', 'Content for each region.')], states: ['closed', 'open', 'nested', 'focus-visible'], accessibility: ['Headless UI supplies focus trap, Escape, restoration, and scroll lock.', 'Header title and description are associated.'], composition: ['Compose ModalOverlay > ModalPanel > ModalHeader, ModalBody, and ModalFooter.'], code: '<ModalOverlay onClose={onClose}><ModalPanel><ModalHeader heading="Settings" onClose={onClose} /><ModalBody>...</ModalBody><ModalFooter>...</ModalFooter></ModalPanel></ModalOverlay>' }),
  doc({ id: 'confirm-dialog', name: 'ConfirmDialog', category: 'Overlays', purpose: 'Confirms a consequential action with explicit cancel and confirm controls.', useWhen: ['Destructive or irreversible actions'], avoidWhen: ['Routine actions that do not need interruption'], api: [row('open', 'boolean', 'required', 'Whether the dialog is shown.'), row('onConfirm', '() => void', 'required', 'Confirm callback.'), row('onCancel', '() => void', 'required', 'Cancel callback.'), row('title', 'string', 'required', 'Dialog heading.'), row('description', 'ReactNode', 'undefined', 'Supporting explanation.'), row('confirmLabel', 'string', 'Confirm', 'Confirm button label.'), row('cancelLabel', 'string', 'Cancel', 'Cancel button label.'), row('destructive', 'boolean', 'false', 'Uses destructive styling.'), row('loading', 'boolean', 'false', 'Disables dismissal while working.'), row('loadingLabel', 'string', 'Working…', 'Busy button label.')], states: ['closed', 'open', 'loading'], accessibility: ['Uses alertdialog semantics.', 'Dismissal is disabled while loading.'], composition: ['Use for a single consequential action with a clear description.'], code: '<ConfirmDialog open={open} title="Delete project?" description="This cannot be undone." onConfirm={remove} onCancel={cancel} destructive />' }),
  doc({ id: 'tooltip', name: 'Tooltip', category: 'Overlays', purpose: 'Provides brief supplemental information for a trigger.', useWhen: ['Clarifying unfamiliar icons or controls'], avoidWhen: ['Essential instructions', 'Long or interactive content'], api: [row('content', 'string', 'required', 'Tooltip text.'), row('position', 'TooltipPosition', 'top', 'top, bottom, left, or right.'), row('delay', 'number', '300', 'Show delay in milliseconds.'), row('children', 'ReactElement', 'required', 'Trigger element.'), row('className', 'string', 'undefined', 'Additional tooltip classes.')], states: ['hidden', 'visible', 'focused', 'touch-visible'], accessibility: ['Adds aria-describedby while visible.', 'Keep essential information outside the tooltip.'], composition: ['Wrap one focusable trigger.'], code: '<Tooltip content="Copy link"><Button variant="icon" aria-label="Copy link">...</Button></Tooltip>' }),
  doc({ id: 'themed-hero-image', name: 'ThemedHeroImage', category: 'Theme & media', purpose: 'Displays a decorative hero image that adapts to the active theme.', useWhen: ['Large decorative hero backgrounds'], avoidWhen: ['Content images that need an alt description'], api: [row('darkSrc', 'string', 'required', 'Dark-theme image source.'), row('lightSrc', 'string', 'undefined', 'Optional light-theme source.'), row('overlay', 'default | strong | soft | none', 'default', 'Overlay treatment.'), row('priority', 'boolean', 'false', 'Next Image priority loading.'), row('quality', 'number', '85', 'Image quality.'), row('sizes', 'string', '100vw', 'Responsive image sizes.'), row('objectPosition', 'string', 'undefined', 'Image object position.'), row('fadeTop', 'boolean', 'false', 'Top fade.'), row('fadeBottom', 'boolean', 'false', 'Bottom fade.'), row('blendLight', 'boolean', 'false', 'Light-theme blend.')], states: ['dark theme', 'light theme'], accessibility: ['Image is intentionally decorative with empty alt text.'], composition: ['Place behind hero content in a positioned container.'], code: '<ThemedHeroImage darkSrc="/hero-dark.jpg" lightSrc="/hero-light.jpg" fadeBottom />' }),
  doc({ id: 'theme', name: 'ThemeProvider / useTheme / ThemeToggle', category: 'Theme & media', purpose: 'Controls and exposes the dark or light visual theme.', useWhen: ['Applications supporting theme preference'], avoidWhen: ['Components that should not own global theme state'], api: [row('ThemeProvider.children', 'ReactNode', 'required', 'Application subtree.'), row('useTheme().theme', 'dark | light', 'dark', 'Current theme.'), row('useTheme().toggleTheme', '() => void', 'undefined', 'Switches and persists the theme.'), row('ThemeToggle', 'component', 'undefined', 'Ready-made theme switch control.')], states: ['dark', 'light'], accessibility: ['ThemeToggle exposes a labelled button.', 'Respect system and saved theme setup before rendering content.'], composition: ['Wrap the app once with ThemeProvider.', 'Use useTheme for custom controls.'], code: '<ThemeProvider><ThemeToggle /><App /></ThemeProvider>' }),
  doc({
    id: 'cn',
    name: 'cn',
    category: 'Utilities & motion',
    purpose: 'Combines conditional class strings and resolves conflicting Tailwind utilities.',
    useWhen: ['A component needs conditional classes or consumer className merging'],
    avoidWhen: ['A static className needs no composition'],
    api: [row('...inputs', 'Array<string | false | null | undefined>', 'required', 'Class fragments in precedence order.')],
    states: ['not applicable'],
    accessibility: ['Class merging must not remove focus, disabled, or semantic state styles.'],
    composition: ['Pass the consumer className last when it should override defaults.'],
    code: 'const classes = cn("rounded-md border", active && "border-red", className);',
  }),
  doc({
    id: 'motion-helpers',
    name: 'Motion helpers',
    category: 'Utilities & motion',
    purpose: 'Keeps Framer Motion timing, offsets, easing, reveals, and hover behavior consistent.',
    useWhen: ['Shared entrance, in-view reveal, stagger, or subtle hover behavior is needed'],
    avoidWhen: ['Motion does not clarify hierarchy or state'],
    api: [
      row('motionDuration', 'readonly timing object', 'shared values', 'Instant, fast, base, reveal, section, and ambient durations.'),
      row('motionOffset', 'readonly offset object', 'shared values', 'Small, medium, large, and hover distances.'),
      row('motionEase', 'readonly easing object', 'shared values', 'Standard, in-out, and out easing.'),
      row('staggerDelay', '(index, step?, base?) => number', 'step 0.1, base 0', 'Calculates a list-item delay.'),
      row('fadeUpMotion', '(delay?, y?, duration?) => MotionProps', 'shared reveal values', 'Returns mount animation props.'),
      row('inViewFadeUpMotion', '(delay?, y?, duration?) => MotionProps', 'shared reveal values', 'Returns one-time viewport reveal props.'),
      row('subtleHoverMotion', '(distance?) => MotionProps', '2px', 'Returns subtle hover lift props.'),
      row('borderHoverMotion', '(distance?, borderColor?) => MotionProps', '4px, border-strong', 'Returns lift plus border emphasis.'),
    ],
    states: ['entry', 'in view', 'hover', 'reduced motion'],
    accessibility: ['ThemeProvider configures Framer Motion to honor the user reduced-motion preference.', 'Never rely on motion alone to communicate meaning.'],
    composition: ['Spread helper results onto a Framer Motion element.'],
    code: '<motion.article {...inViewFadeUpMotion(staggerDelay(index))}>...</motion.article>',
  }),
];
